
import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'nl' | 'en' | 'de' | 'fr' | 'es';

const translations: Record<Language, Record<string, string>> = {
  nl: {
    // Menu & Tabs
    dashboard: "Dashboard",
    inventory: "Voorraad",
    printHistory: "Logboek",
    printers: "Printers",
    shopping: "Inkooplijst",
    printPreview: "Print Preview",
    showcaseTitle: "Showcase",
    supportTitle: "Steun Project",
    settings: "Instellingen",
    admin: "Admin Dashboard",
    menu: "Menu",
    menuManagement: "Overzicht & Beheer",
    menuTools: "Tools",
    menuPremium: "Premium",
    becomePro: "Word PRO",
    userRatingText: "Gebruikers beoordelen ons met een",
    madeBy: "Gemaakt door",
    notifications: "Notificaties",
    
    // Dashboard Tiles
    totalSpools: "Totaal Spoelen",
    totalWeight: "Totaal Gewicht",
    totalValue: "Totale Waarde",
    lowStock: "Lage Voorraad",
    materialDistribution: "Materiaal Verdeling",
    lowestStock: "Laagste Voorraad",
    investmentBrand: "Investering per Merk",
    successRate: "Succes Ratio",
    items: "items",
    noData: "Geen data beschikbaar",
    proFeatureLocked: "PRO Functie",
    upgradeToUnlock: "Upgrade om te ontgrendelen",
    filament: "Filament",
    materials: "Materialen",

    // Print Preview Page
    dropGcode: "Sleep je G-code hierheen",
    autoCalculatedDesc: "Voorraad en AMS slots worden automatisch gecontroleerd.",
    configuration: "Configuratie",
    printQuantity: "Aantal afdrukken",
    selectPrinterFirst: "Selecteer eerst een printer...",
    waitingForPrinter: "Wachten op printer",
    waitingForPrinterDesc: "Kies een printer om de AMS status te controleren.",
    readyToPrint: "Klaar voor print!",
    notReadyToPrint: "Niet klaar",
    checkAlertsBelow: "Controleer de meldingen hieronder.",
    checkStock: "Voorraad controle",
    totalRequired: "Totaal nodig",
    perfectMatch: "Perfecte match",
    noMatchingSpool: "Geen passende spoel gevonden",
    inStock: "Op voorraad",
    insufficientStock: "Onvoldoende voorraad",
    proposedSlot: "Voorgesteld slot",
    slot: "Slot",
    loadFromStock: "Laden uit voorraad",
    notInAms: "Niet in AMS gevonden",
    
    // Actions & Common
    save: "Opslaan",
    cancel: "Annuleren",
    delete: "Verwijder",
    edit: "Bewerk",
    close: "Sluiten",
    back: "Terug",
    success: "Gelukt",
    failed: "Mislukt",
    loading: "Laden...",
    confirmDelete: "Weet je zeker dat je dit wilt verwijderen?",
    winterEdition: "Winter Editie",

    // Notifications Page
    notificationsSubtitle: "Blijf op de hoogte van nieuwe functies en updates.",
    noNotifications: "Geen nieuwe meldingen",
    allCaughtUp: "Je bent helemaal bij!",
    newUpdate: "Nieuwe Update!",
    versionActive: "Versie %v is nu actief",
    installed: "Geïnstalleerd",
    whatsNew: "Wat is er nieuw",
    autoUpdateMsg: "De app is automatisch bijgewerkt naar de hoogste versie.",
    publishedOn: "Gepubliceerd op",
    security: "Veiligheid",
    securityDesc: "Updates bevatten vaak belangrijke beveiligingsverbeteringen.",
    speed: "Snelheid",
    speedDesc: "We optimaliseren de app constant voor een snellere ervaring."
  },
  en: {
    dashboard: "Dashboard",
    inventory: "Inventory",
    printHistory: "Print History",
    printers: "Printers",
    shopping: "Shopping List",
    printPreview: "Print Preview",
    showcaseTitle: "Showcase",
    supportTitle: "Support Project",
    settings: "Settings",
    admin: "Admin Panel",
    menu: "Menu",
    menuManagement: "Management",
    menuTools: "Tools",
    menuPremium: "Premium",
    becomePro: "Become PRO",
    userRatingText: "Users rate us with a",
    madeBy: "Made by",
    notifications: "Notifications",
    
    totalSpools: "Total Spools",
    totalWeight: "Total Weight",
    totalValue: "Total Value",
    lowStock: "Low Stock",
    materialDistribution: "Material Distribution",
    lowestStock: "Lowest Stock",
    investmentBrand: "Investment per Brand",
    successRate: "Success Rate",
    items: "items",
    noData: "No data available",
    proFeatureLocked: "PRO Feature",
    upgradeToUnlock: "Upgrade to unlock",
    filament: "Filament",
    materials: "Materials",

    dropGcode: "Drop your G-code here",
    autoCalculatedDesc: "Stock and AMS slots will be checked automatically.",
    configuration: "Configuration",
    printQuantity: "Print Quantity",
    selectPrinterFirst: "Select a printer first...",
    waitingForPrinter: "Waiting for printer",
    waitingForPrinterDesc: "Choose a printer to check AMS status.",
    readyToPrint: "Ready to print!",
    notReadyToPrint: "Not ready",
    checkAlertsBelow: "Please check the alerts below.",
    checkStock: "Stock Check",
    totalRequired: "Total required",
    perfectMatch: "Perfect match",
    noMatchingSpool: "No matching spool found",
    inStock: "In stock",
    insufficientStock: "Insufficient stock",
    proposedSlot: "Proposed slot",
    slot: "Slot",
    loadFromStock: "Load from stock",
    notInAms: "Not found in AMS",

    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    close: "Close",
    back: "Back",
    success: "Success",
    failed: "Failed",
    loading: "Loading...",
    confirmDelete: "Are you sure you want to delete this?",
    winterEdition: "Winter Edition",
    notificationsSubtitle: "Stay updated with new features and improvements.",
    noNotifications: "No new notifications",
    allCaughtUp: "You're all caught up!",
    newUpdate: "New Update!",
    versionActive: "Version %v is now active",
    installed: "Installed",
    whatsNew: "What's New",
    autoUpdateMsg: "The app has been automatically updated to the latest version.",
    publishedOn: "Published on",
    security: "Security",
    securityDesc: "Updates often include important security enhancements.",
    speed: "Performance",
    speedDesc: "We constantly optimize the app for a faster experience."
  },
  de: {
    dashboard: "Dashboard",
    inventory: "Inventar",
    printHistory: "Logbuch",
    printers: "Drucker",
    shopping: "Einkaufsliste",
    printPreview: "Druckvorschau",
    showcaseTitle: "Schaukasten",
    supportTitle: "Projekt unterstützen",
    settings: "Einstellungen",
    admin: "Admin-Bereich",
    menu: "Menü",
    menuManagement: "Übersicht & Verwaltung",
    menuTools: "Werkzeuge",
    menuPremium: "Premium",
    becomePro: "PRO werden",
    userRatingText: "Nutzer bewerten uns mit",
    madeBy: "Erstellt von",
    notifications: "Benachrichtigungen",
    
    totalSpools: "Gesamtspulen",
    totalWeight: "Gesamtgewicht",
    totalValue: "Gesamtwert",
    lowStock: "Niedriger Bestand",
    materialDistribution: "Materialverteilung",
    lowestStock: "Niedrigster Bestand",
    investmentBrand: "Investition pro Marke",
    successRate: "Erfolgsquote",
    items: "Artikel",
    noData: "Keine Daten verfügbar",
    proFeatureLocked: "PRO Funktion",
    upgradeToUnlock: "Upgrade zum Freischalten",
    filament: "Filament",
    materials: "Materialien",

    dropGcode: "G-Code Datei hierher ziehen",
    autoCalculatedDesc: "Bestand und AMS-Steckplätze werden automatisch geprüft.",
    configuration: "Konfiguration",
    printQuantity: "Anzahl Drucke",
    selectPrinterFirst: "Zuerst Drucker auswählen...",
    waitingForPrinter: "Warten auf Drucker",
    waitingForPrinterDesc: "Wählen Sie einen Drucker, um den AMS-Status zu prüfen.",
    readyToPrint: "Druckbereit!",
    notReadyToPrint: "Nicht bereit",
    checkAlertsBelow: "Bitte prüfen Sie die Warnungen unten.",
    checkStock: "Bestandsprüfung",
    totalRequired: "Gesamtbedarf",
    perfectMatch: "Perfektes Match",
    noMatchingSpool: "Keine passende Spule gefunden",
    inStock: "Auf Lager",
    insufficientStock: "Unzureichender Bestand",
    proposedSlot: "Vorgeschlagener Slot",
    slot: "Slot",
    loadFromStock: "Vom Lager laden",
    notInAms: "Nicht im AMS gefunden",

    save: "Speichern",
    cancel: "Abbrechen",
    delete: "Löschen",
    edit: "Bearbeiten",
    close: "Schließen",
    back: "Zurück",
    success: "Erfolgreich",
    failed: "Fehlgeschlagen",
    loading: "Laden...",
    confirmDelete: "Sind Sie sicher, dass Sie dies löschen möchten?",
    winterEdition: "Winter-Edition",
    notificationsSubtitle: "Bleiben Sie over neue Funktionen und Verbesserungen auf dem Laufenden.",
    noNotifications: "Keine neuen Benachrichtigungen",
    allCaughtUp: "Alles ist auf dem neuesten Stand!",
    newUpdate: "Neues Update!",
    versionActive: "Version %v ist jetzt aktiv",
    installed: "Installiert",
    whatsNew: "Was ist neu",
    autoUpdateMsg: "Die app wurde automatisch aktualisiert.",
    publishedOn: "Veröffentlicht am",
    security: "Sicherheit",
    securityDesc: "Updates enthalten oft wichtige Sicherheitsverbesserungen.",
    speed: "Leistung",
    speedDesc: "Wir optimieren die App ständig."
  },
  fr: {
    dashboard: "Tableau de bord",
    inventory: "Inventaire",
    printHistory: "Journal de bord",
    printers: "Imprimantes",
    shopping: "Liste d'achats",
    printPreview: "Aperçu",
    showcaseTitle: "Vitrine",
    supportTitle: "Soutenir le projet",
    settings: "Paramètres",
    admin: "Admin",
    menu: "Menu",
    menuManagement: "Gestion",
    menuTools: "Outils",
    menuPremium: "Premium",
    becomePro: "Devenir PRO",
    userRatingText: "Les utilisateurs nous notent",
    madeBy: "Fait par",
    notifications: "Notifications",
    
    totalSpools: "Total Bobines",
    totalWeight: "Poids Total",
    totalValue: "Valeur Totale",
    lowStock: "Stock Faible",
    materialDistribution: "Distribution des Matériaux",
    lowestStock: "Stock le plus bas",
    investmentBrand: "Investissement par Marque",
    successRate: "Taux de Réussite",
    items: "articles",
    noData: "Aucune donnée disponible",
    proFeatureLocked: "Fonction PRO",
    upgradeToUnlock: "Mettre à jour pour débloquer",
    filament: "Filament",
    materials: "Matériaux",

    dropGcode: "Déposez votre fichier G-code ici",
    autoCalculatedDesc: "Le stock et les emplacements AMS seront vérifiés automatiquement.",
    configuration: "Configuration",
    printQuantity: "Quantité d'impressions",
    selectPrinterFirst: "Sélectionnez une imprimante d'abord...",
    waitingForPrinter: "En attente d'imprimante",
    waitingForPrinterDesc: "Choisissez une imprimante pour vérifier l'état de l'AMS.",
    readyToPrint: "Prêt à imprimer !",
    notReadyToPrint: "Pas prêt",
    checkAlertsBelow: "Veuillez vérifier les alertes ci-dessous.",
    checkStock: "Contrôle du stock",
    totalRequired: "Total requis",
    perfectMatch: "Correspondance parfaite",
    noMatchingSpool: "Aucune bobine correspondante trouvée",
    inStock: "En stock",
    insufficientStock: "Stock insuffisant",
    proposedSlot: "Emplacement proposé",
    slot: "Slot",
    loadFromStock: "Charger depuis le stock",
    notInAms: "Non trouvé dans l'AMS",

    save: "Enregistrer",
    cancel: "Annuler",
    delete: "Supprimer",
    edit: "Modifier",
    close: "Fermer",
    back: "Retour",
    success: "Succès",
    failed: "Échec",
    loading: "Chargement...",
    confirmDelete: "Êtes-vous sûr de vouloir supprimer ceci?",
    winterEdition: "Édition d'hiver",
    notificationsSubtitle: "Restez au courant des nouvelles fonctionnalités.",
    noNotifications: "Pas de nouvelles notifications",
    allCaughtUp: "Vous êtes à jour !",
    newUpdate: "Nouvelle mise à jour !",
    versionActive: "La version %v est maintenant active",
    installed: "Installé",
    whatsNew: "Quoi de neuf",
    autoUpdateMsg: "L'application a été automatiquement mise à jour.",
    publishedOn: "Publié le",
    security: "Sécurité",
    securityDesc: "Les mises à jour incluent des améliorations de sécurité.",
    speed: "Performance",
    speedDesc: "Nous optimisons constamment l'application."
  },
  es: {
    dashboard: "Panel",
    inventory: "Inventario",
    printHistory: "Historial",
    printers: "Impresoras",
    shopping: "Lista de compras",
    printPreview: "Vista previa",
    showcaseTitle: "Vitrina",
    supportTitle: "Apoyar proyecto",
    settings: "Ajustes",
    admin: "Admin",
    menu: "Menú",
    menuManagement: "Gestión",
    menuTools: "Herramientas",
    menuPremium: "Premium",
    becomePro: "Hacerse PRO",
    userRatingText: "Los usuarios nos califican con",
    madeBy: "Hecho por",
    notifications: "Notificaciones",
    
    totalSpools: "Total Bobinas",
    totalWeight: "Peso Total",
    totalValue: "Valor Total",
    lowStock: "Stock Bajo",
    materialDistribution: "Distribución de Materiales",
    lowestStock: "Stock más bajo",
    investmentBrand: "Inversión por Marca",
    successRate: "Tasa de Éxito",
    items: "artículos",
    noData: "No hay datos disponibles",
    proFeatureLocked: "Función PRO",
    upgradeToUnlock: "Actualizar para desbloquear",
    filament: "Filamento",
    materials: "Materiales",

    dropGcode: "Suelta tu archivo G-code aquí",
    autoCalculatedDesc: "El stock y los slots de AMS se verificarán automáticamente.",
    configuration: "Configuración",
    printQuantity: "Cantidad de impresiones",
    selectPrinterFirst: "Selecciona una impresora primero...",
    waitingForPrinter: "Esperando impresora",
    waitingForPrinterDesc: "Elige una impresora para verificar el estado de AMS.",
    readyToPrint: "¡Listo para imprimir!",
    notReadyToPrint: "No listo",
    checkAlertsBelow: "Por favor, revisa las alertas de abajo.",
    checkStock: "Control de stock",
    totalRequired: "Total requerido",
    perfectMatch: "Coincidencia perfecta",
    noMatchingSpool: "No se encontró bobina coincidente",
    inStock: "En stock",
    insufficientStock: "Stock insuficiente",
    proposedSlot: "Slot propuesto",
    slot: "Slot",
    loadFromStock: "Cargar desde el stock",
    notInAms: "No encontrado en AMS",

    save: "Guardar",
    cancel: "Cancelar",
    delete: "Eliminar",
    edit: "Editar",
    close: "Cerrar",
    back: "Volver",
    success: "Éxito",
    failed: "Error",
    loading: "Cargando...",
    confirmDelete: "¿Estás seguro de que quieres eliminar esto?",
    winterEdition: "Edición de invierno",
    notificationsSubtitle: "Mantente al día con las nuevas funciones.",
    noNotifications: "No hay notificaciones nuevas",
    allCaughtUp: "¡Estás al día!",
    newUpdate: "¡Nueva actualización!",
    versionActive: "La version %v ya está activa",
    installed: "Instalado",
    whatsNew: "Novedades",
    autoUpdateMsg: "La aplicación se ha actualizado automáticamente.",
    publishedOn: "Publicado el",
    security: "Seguridad",
    securityDesc: "Las actualizaciones incluyen mejoras de seguridad.",
    speed: "Rendimiento",
    speedDesc: "Optimizamos constantemente la aplicación."
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  tColor: (color: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    return (localStorage.getItem('app_language') as Language) || 'nl';
  });

  useEffect(() => {
    localStorage.setItem('app_language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    if (!key) return '';
    return translations[language][key] || translations['en'][key] || key;
  };

  const tColor = (color: string): string => {
    if (!color) return '';
    const lowerColor = color.toLowerCase();
    return translations[language][lowerColor] || translations['en'][lowerColor] || color;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, tColor }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
