import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'nl' | 'en' | 'de' | 'fr' | 'es';

const translations: Record<Language, Record<string, string>> = {
  nl: {
    // Menu & Tabs
    inventory: "Voorraad",
    filaments: "Filamenten",
    materials: "Materialen",
    locations: "Locaties",
    suppliers: "Leveranciers",
    printers: "Printers",
    shopping: "Inkooplijst",
    settings: "Instellingen",
    logout: "Uitloggen",
    menu: "Menu",
    menuManagement: "Overzicht & Beheer",
    menuTools: "Tools",
    menuPremium: "Premium",
    loggedInAs: "Ingelogd als",
    madeBy: "Gemaakt door",
    feedback: "Feedback",
    printHistory: "Logboek",
    dashboard: "Dashboard",
    supportTitle: "Steun Project",
    admin: "Admin Dashboard",
    becomePro: "Word PRO",
    help: "Hulp & Contact",
    userRatingText: "Gebruikers beoordelen ons met een",
    showcaseTitle: "Showcase",
    spools: "Spoelen & Gewichten",
    requests: "Verzoeken",
    notifications: "Meldingen",
    labels: "Labels Printen",
    printPreview: "Print Preview",
    
    // Global / Common
    save: "Opslaan",
    cancel: "Annuleren",
    delete: "Verwijder",
    edit: "Bewerk",
    close: "Sluiten",
    back: "Terug",
    next: "Volgende",
    finish: "Afronden",
    loading: "Laden...",
    search: "Zoeken",
    filter: "Filteren",
    sort: "Sorteren",
    actions: "Acties",
    name: "Naam",
    description: "Omschrijving",
    optional: "Optioneel",
    website: "Website",
    date: "Datum",
    status: "Status",
    success: "Gelukt",
    failed: "Mislukt",
    unknown: "Onbekend",
    all: "Alles",
    none: "Geen",
    selected: "geselecteerd",
    send: "Versturen",
    markAsRead: "Markeer als gelezen",
    markAsUnread: "Markeer als ongelezen",
    add: "Toevoegen",
    filtered: "Gefilterd",
    stock: "Voorraad",
    minutes: "minuten",
    slot: "Slot",
    confirmDelete: "Weet je zeker dat je dit wilt verwijderen?",
    
    // Inventory & Form
    searchPlaceholder: "Zoek op merk, kleur, materiaal of ID...",
    newFilament: "Nieuw Filament",
    formNewTitle: "Nieuw Filament",
    formEditTitle: "Filament Bewerken",
    newMaterial: "Nieuw Materiaal",
    allStocked: "Alles is op voorraad!",
    allStockedDesc: "Er zijn geen items onder de minimum voorraad.",
    noFilaments: "Geen filamenten gevonden.",
    noMaterials: "Geen materialen gevonden.",
    weightRemaining: "Resterend",
    viewSpools: "Bekijk spoelen",
    order: "Bestellen",
    searchGoogle: "Zoeken op Google",
    totalWeight: "Totaal Gewicht",
    items: "items",
    lowStock: "Bijna Leeg",
    totalValue: "Totale Waarde",
    totalCosts: "Totale Kosten",
    totalSpools: "Totaal Spoelen",
    successRate: "Succes Ratio",
    materialDistribution: "Materiaal Verdeling",
    lowestStock: "Laagste Voorraad",
    investmentBrand: "Investering per Merk",
    noData: "Geen data beschikbaar",
    winterEdition: "Winter Editie",
    proFeatureLocked: "PRO Functie",
    upgradeToUnlock: "Upgrade om te ontgrenelen",
    printLabel: "Print Label",
    scanLabel: "Scan Label",
    scanInstruction: "Scan de QR-code of het etiket op de spoel",
    scanTitle: "Slimme Scanner",
    scanDesc: "Scan een spoel om deze direct op te zoeken of toe te voegen.",
    lookupMode: "Zoekmodus",
    lookupFound: "Spoel gevonden!",
    lookupNotFound: "Geen spoel gevonden met dit ID.",
    
    // Print Preview
    dropGcode: "Sleep je G-code hierheen of klik om te laden",
    checkStock: "Voorraad Check",
    requiredFilament: "Benodigd Filament",
    inStock: "In Voorraad",
    insufficientStock: "Onvoldoende Voorraad",
    inAms: "In AMS/CFS",
    notInAms: "Niet in AMS",
    readyToPrint: "Klaar voor print!",
    notReadyToPrint: "Niet klaar voor print",
    checkAlertsBelow: "Check de rode meldingen hieronder.",
    printQuantity: "Aantal prints",
    totalRequired: "Totaal benodigd",
    selectPrinterFirst: "Kies eerst een printer...",
    noMatchingSpool: "Geen match gevonden",
    multipleMatches: "Meerdere matches",
    configuration: "Configuratie",
    waitingForPrinter: "Wacht op printer...",
    waitingForPrinterDesc: "Selecteer een printer om de voorraad- en AMS-check te voltooien.",
    proposedSlot: "Voorgesteld Slot",
    loadFromStock: "Laden uit voorraad",
    perfectMatch: "Perfecte match",
    colorMismatch: "Kleur wijkt af",

    // Showcase
    showcaseSubtitle: "Deel je voorraad met anderen",
    showcaseName: "Jouw Publieke Naam",
    previewShowcase: "Bekijk Preview",
    publicStock: "Publieke Voorraad",
    availableItems: "Beschikbare items",
    loginClose: "Login / Sluiten",
    showcaseFilterLabel: "Welk filament tonen?",
    showcaseEverything: "Alles Tonen",
    showcaseFilterDesc: "Selecteer materialen om de link te filteren. Niets geselecteerd = Alles zichtbaar.",
    showcaseLinkTitle: "Jouw Unieke Link",
    showcasePrivacyTitle: "Privacy Info",
    showcasePrivacyDesc: "Bezoekers zien alleen merk, materiaal, kleur en beschikbaarheid. Prijzen, locaties en notities blijven altijd privé.",
    copyLink: "Kopieer Link",

    // Notifications Page
    notificationsSubtitle: "Blijf op de hoogte van nieuwe functies en updates.",
    noNotifications: "Geen nieuwe meldingen",
    allCaughtUp: "Je bent helemaal bij!",
    newUpdate: "Nieuwe Update!",
    versionActive: "Versie %v is nu actief",
    installed: "Geïnstalleerd",
    whatsNew: "Wat is er nieuw",
    autoUpdateMsg: "De app is automatisch bijgewerkt naar de nieuwste versie.",
    publishedOn: "Gepubliceerd op",
    security: "Veiligheid",
    securityDesc: "Updates bevatten vaak belangrijke beveiligingsverbeteringen.",
    speed: "Snelheid",
    speedDesc: "We optimaliseren de app constant voor een snellere ervaring.",

    // Logbook
    recentActivity: "Recente Activiteit",
    exportCsv: "Exporteer CSV",
    logPrint: "Print Loggen",
    dragDrop: "Sleep je G-code hierheen of klik om te uploaden",
    noHistory: "Nog geen printgeschiedenis gevonden.",
    netCost: "Netto Kosten",
    sellPrice: "Verkoopprijs",
    projectName: "Projectnaam",
    projectNamePlaceholder: "bv. Baby Yoda",
    timeOptional: "Tijd (Optioneel)",
    exampleTime: "bv. 2h 45m",
    usedMaterials: "Gebruikte Filamenten",
    addSlot: "Slot Toevoegen",
    manualEntry: "Of voer handmatig gegevens in",
    saveUpdate: "Opslaan & Voorraad Bijwerken",
    analyzing: "G-code Analyseren...",
    overrideWeight: "Totaal Gewicht Overschrijven",
    autoCalculated: "Wordt automatisch berekend",
    details: "Details",
    weight: "Gewicht",
    duration: "Duur",
    assemblyTimeLabel: "Assemblage Tijd",
    otherMaterials: "Overige Materialen",
    noExtraMaterials: "Geen extra materialen toegevoegd.",
    searchMaterial: "Zoek materiaal...",
    electricity: "Stroom",
    depreciation: "Afschrijving",
    labor: "Arbeid/Opslag",
    profitMarginLabel: "Winstmarge",
    rounding: "Afronding",
    noDetailedCost: "No detailed costs available for this print.",
    unknownMaterial: "Onbekend materiaal",

    // Settings
    tabGeneral: "Algemeen",
    tabNotifications: "Meldingen",
    tabData: "Data & Backup",
    tabAccount: "Account",
    tabPro: "Pro Tools",
    tabManagement: "Beheer",
    appearance: "Weergave",
    darkMode: "Donker",
    lightMode: "Licht",
    language: "Taal",
    lowStockWarning: "Laag Voorraad Waarschuwing",
    unusedWarning: "Lang niet gebruikt",
    days: "dagen",
    backupCreate: "Backup Maken",
    backupRestore: "Backup Terugzetten",
    dangerZone: "Gevarenzone",
    deleteAccount: "Account Verwijderen",
    deleteAccountDesc: "Dit verwijdert al je data permanent. Dit kan niet worden teruggedraaid.",
    cancelDeletion: "Verzoek Annuleren",
    requestSent: "Verzoek verstuurd. Je data wordt binnen 48 uur verwijderd.",
    requestCancelled: "Verwijderverzoek geannuleerd.",
    proTools: "Pro Tools",
    proToolsDesc: "Vul hier je kosten in om de verkoopprijs van je prints automatisch te berekenen.",
    electricityRate: "Stroomtarief (€/kWh)",
    hourlyRate: "Uurtarief (€/uur)",
    profitMargin: "Winstmarge (%)",
    roundToNine: "Afronden op .x9",
    exampleElectricityRate: "bv. 0.35",
    exampleHourlyRate: "bv. 2.00",
    roundingLabel: "Afronding",
    privacyPolicy: "Privacyverklaring",
    donateButton: "Steun Project",
    stayLoggedIn: "Ingelogd blijven",
    locationManager: "Locatiebeheer",
    addLocation: "Locatie Toevoegen",
    exampleLocation: "bv. Werkplaats",
    noLocations: "Geen locaties gevonden.",
    supplierManager: "Leveranciersbeheer",
    addSupplier: "Leverancier Toevoegen",
    exampleSupplier: "bv. 123-3D",
    exampleWebsite: "bv. www.mijnwinkel.nl",
    noSuppliers: "Geen leveranciers gevonden.",
    winterEditionDesc: "Laat het sneeuwen in de app!",
    aboutApp: "Over de app",
    proComingSoonMsg: "Deze functie komt binnenkort beschikbaar voor PRO leden.",
    
    // Support Page
    supportPageTitle: "Steun dit project",
    supportPageSubtitle: "Help mee om de servers online te houden en de app te verbeteren.",
    serverCosts: "Server Kosten",
    serverCostsDesc: "Je bijdrage helpt direct bij het betalen van de database en hosting.",
    development: "Ontwikkeling",
    developmentDesc: "Nieuwe functies zoals de AI-scanner kosten tijd en rekenkracht.",
    adFree: "100% Reclamevrij",
    adFreeDesc: "Geen vervelende ads, alleen tools voor makers.",
    thankYouNote: "Bedankt voor je support!",

    // Forms Common
    brand: "Merk",
    color: "Kleur",
    material: "Materiaal",
    category: "Categorie",
    quantity: "Aantal",
    unit: "Eenheid",
    price: "Prijs",
    notes: "Notities",
    weightTotalLabel: "Totaal (g)",
    weightRemainingLabel: "Resterend (g)",
    tempNozzle: "Nozzle (°C)",
    tempBed: "Bed (°C)",
    location: "Locatie",
    supplier: "Leverancier",
    shopUrl: "Winkel URL",
    addMultiple: "Aantal Spoelen Toevoegen",
    saveChanges: "Wijzigingen Opslaan",
    addToInventory: "Toevoegen aan Voorraad",
    clear: "Wissen",
    selectBrand: "Kies merk...",
    otherBrand: "+ Ander merk...",
    selectMaterial: "Kies materiaal...",
    otherMaterial: "+ Ander materiaal...",
    selectColor: "Kies kleur...",
    otherColor: "+ Andere kleur...",
    colorNamePlaceholder: "Kleurnaam",
    newLocationPlaceholder: "Nieuwe locatie...",
    newSupplierPlaceholder: "Nieuwe leverancier...",
    newLocationOption: "+ Nieuwe Locatie...",
    newSupplierOption: "+ Nieuwe Leverancier...",

    // Weigh Helper
    weighHelper: "Weeg Hulp",
    grossWeight: "Bruto Gewicht",
    spoolType: "Type Lege Spoel",
    tareWeight: "Tarra Gewicht",
    apply: "Overnemen",
    suggestSpool: "Staat jouw spoel er niet tussen?",
    result: "Resultaat",

    // Auth
    invalidCredentials: "Ongeldig emailadres of wachtwoord.",
    exampleEmail: "bv. info@voorbeeld.nl",
    passwordPlaceholder: "Je wachtwoord",

    // Colors
    "zwart": "Zwart",
    "wit": "Wit",
    "grijs": "Grijs",
    "zilver": "Zilver",
    "rood": "Rood",
    "blauw": "Blauw",
    "groen": "Groen",
    "geel": "Geel",
    "oranje": "Oranje",
    "paars": "Paars",
    "roze": "Roze",
    "goud": "Goud",
    "brons": "Brons",
    "transparant": "Transparant",
    "naturel": "Naturel"
  },
  en: {
    printPreview: "Print Preview",
    dropGcode: "Drop your G-code here or click to load",
    checkStock: "Stock Check",
    requiredFilament: "Required Filament",
    inStock: "In Stock",
    insufficientStock: "Insufficient Stock",
    inAms: "In AMS/CFS",
    notInAms: "Not in AMS",
    readyToPrint: "Ready to print!",
    notReadyToPrint: "Not ready to print",
    checkAlertsBelow: "Check the red alerts below.",
    printQuantity: "Print Quantity",
    totalRequired: "Total required",
    selectPrinterFirst: "Select a printer first...",
    noMatchingSpool: "No matching spool",
    multipleMatches: "Multiple matches",
    configuration: "Configuration",
    waitingForPrinter: "Waiting for printer...",
    waitingForPrinterDesc: "Select a printer to complete the stock and AMS check.",
    proposedSlot: "Proposed Slot",
    loadFromStock: "Load from stock",
    perfectMatch: "Perfect match",
    colorMismatch: "Color mismatch"
  },
  de: {
    printPreview: "Druckvorschau",
    dropGcode: "G-Code hierher ziehen oder klicken",
    checkStock: "Lagerprüfung",
    requiredFilament: "Benötigtes Filament",
    inStock: "Auf Lager",
    insufficientStock: "Unzureichender Vorrat",
    inAms: "Im AMS/CFS",
    notInAms: "Nicht im AMS",
    readyToPrint: "Bereit zum Drucken!",
    notReadyToPrint: "Nicht bereit zum Drucken",
    checkAlertsBelow: "Überprüfen Sie die roten Warnungen unten.",
    printQuantity: "Anzahl der Drucke",
    totalRequired: "Insgesamt benötigt",
    selectPrinterFirst: "Zuerst Drucker wählen...",
    noMatchingSpool: "Keine Übereinstimmung",
    multipleMatches: "Mehrere Treffer",
    configuration: "Konfiguration",
    waitingForPrinter: "Warten auf Drucker...",
    waitingForPrinterDesc: "Wählen Sie einen Drucker aus, um die Bestands- und AMS-Prüfung abzuschließen.",
    proposedSlot: "Vorgeschlagener Slot",
    loadFromStock: "Aus Vorraad laden"
  },
  fr: {
    printPreview: "Aperçu d'impression",
    dropGcode: "Déposez votre G-code ici ou cliquez",
    checkStock: "Vérification du stock",
    requiredFilament: "Filament requis",
    inStock: "En stock",
    insufficientStock: "Stock insuffisant",
    inAms: "Dans l'AMS/CFS",
    notInAms: "Pas dans l'AMS",
    readyToPrint: "Prêt à imprimer !",
    notReadyToPrint: "Pas prêt à imprimer",
    checkAlertsBelow: "Vérifiez les alertes rouges ci-dessous.",
    printQuantity: "Nombre d'impressions",
    totalRequired: "Total requis",
    selectPrinterFirst: "Choisissez d'abord une imprimante...",
    noMatchingSpool: "Aucune correspondance",
    multipleMatches: "Plusieurs correspondances",
    configuration: "Configuration",
    waitingForPrinter: "En attente de l'imprimante...",
    waitingForPrinterDesc: "Sélectionnez une imprimante pour terminer la vérification du stock et de l'AMS.",
    proposedSlot: "Emplacement suggéré",
    loadFromStock: "Charger depuis le stock"
  },
  es: {
    printPreview: "Vista previa de impresión",
    dropGcode: "Arrastre su G-code aquí o haga clic",
    checkStock: "Verificación de stock",
    requiredFilament: "Filamento requerido",
    inStock: "En stock",
    insufficientStock: "Stock insuficiente",
    inAms: "En el AMS/CFS",
    notInAms: "No en el AMS",
    readyToPrint: "¡Listo para imprimir!",
    notReadyToPrint: "No listo para imprimir",
    checkAlertsBelow: "Revise las alertas rojas a continuación.",
    printQuantity: "Número de impresiones",
    totalRequired: "Total necesario",
    selectPrinterFirst: "Elija una impresora primero...",
    noMatchingSpool: "Sin coincidencias",
    multipleMatches: "Varias coincidencias",
    configuration: "Configuración",
    waitingForPrinter: "Esperando impresora...",
    waitingForPrinterDesc: "Seleccione una impresora para completar la comprobación de stock en el AMS.",
    proposedSlot: "Ranura sugerida",
    loadFromStock: "Cargar desde stock"
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  tColor: (color: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Fix: Export LanguageProvider
export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    return (localStorage.getItem('app_language') as Language) || 'nl';
  });

  useEffect(() => {
    localStorage.setItem('app_language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    if (!key) return '';
    return translations[language][key] || translations['en'][key] || key;
  };

  const tColor = (color: string): string => {
    if (!color) return '';
    const lowerColor = color.toLowerCase();
    return translations[language][lowerColor] || translations['en'][lowerColor] || color;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, tColor }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Fix: Export useLanguage hook
export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
