
import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'nl' | 'en' | 'de' | 'fr' | 'es';

const translations: Record<Language, Record<string, string>> = {
  nl: {
    // Menu & Tabs
    dashboard: "Dashboard",
    inventory: "Voorraad",
    printHistory: "Logboek",
    printers: "Printers",
    shopping: "Inkooplijst",
    printPreview: "Print Preview",
    showcaseTitle: "Showcase",
    supportTitle: "Steun Project",
    settings: "Instellingen",
    admin: "Admin Dashboard",
    menu: "Menu",
    menuManagement: "Overzicht & Beheer",
    menuTools: "Tools",
    menuPremium: "Premium",
    becomePro: "Word PRO",
    userRatingText: "Gebruikers beoordelen ons met een",
    madeBy: "Gemaakt door",
    notifications: "Notificaties",
    
    // Settings Sections (Tegels)
    tabGeneral: "Algemeen",
    tabNotifications: "Meldingen",
    tabManagement: "Beheer",
    tabAccount: "Account",
    tabPro: "PRO",
    appearance: "Uiterlijk",
    winterEdition: "Winter Editie",
    winterEditionDesc: "Sneeuwvlokken op het dashboard",
    language: "Taal",
    aboutApp: "Over de App",
    help: "Hulp & Ondersteuning",
    privacyPolicy: "Privacyverklaring",
    donateButton: "Koop een koffie",
    lowStockWarning: "Lage Voorraad Waarschuwing",
    unusedWarning: "Ongebruikt Waarschuwing",
    days: "dagen",
    enableUpdateNotifications: "Ontvang meldingen over nieuwe versies",
    logout: "Uitloggen",
    tabData: "Gegevensbeheer",
    backupCreate: "Backup Maken",
    backupRestore: "Backup Herstellen",
    dangerZone: "Gevarenzone",
    deleteAccount: "Account Verwijderen",
    deleteAccountDesc: "Verwijder al je gegevens definitief uit onze database.",
    cancelDeletion: "Verwijdering Annuleren",
    requestSent: "Verzoek ingediend",
    requestCancelled: "Verzoek geannuleerd",
    confirmCancelDeletion: "Weet je zeker dat je het verwijderverzoek wilt intrekken?",
    proTools: "PRO Calculator Tools",
    proToolsDesc: "Stel hier je tarieven in voor de automatische kostenberekening.",
    electricityRate: "Elektriciteitsprijs (€/kWh)",
    hourlyRate: "Uurtarief / Arbeid (€/u)",
    profitMargin: "Winstmarge (%)",
    roundToNine: "Prijzen afronden op .x9",
    exampleElectricityRate: "bijv. 0.35",
    exampleHourlyRate: "bijv. 2.50",
    proFeatureLocked: "PRO Functie Vergrendeld",
    upgradeToUnlock: "Upgrade naar PRO om dit te gebruiken",
    locationManager: "Locatie Beheer",
    addLocation: "Locatie Toevoegen",
    supplierManager: "Leverancier Beheer",
    addSupplier: "Leverancier Toevoegen",
    optional: "Optioneel",
    exampleLocation: "bijv. Kast A, Plank 2",
    exampleSupplier: "bijv. 123-3D",
    exampleWebsite: "bijv. www.123-3d.nl",
    confirmBackup: "Weet je zeker dat je een backup wilt importeren? Je huidige gegevens worden overschreven.",
    
    // Deletion Reasons
    reasonNotUsing: "Ik gebruik de app niet meer",
    reasonMissingFeatures: "Ik mis functionaliteiten",
    reasonTooComplicated: "De app is te ingewikkeld",
    reasonOtherApp: "Ik heb een andere app gevonden",
    reasonTechnicalIssues: "Technische problemen",
    reasonOther: "Anders...",

    // Common Actions
    save: "Opslaan",
    cancel: "Annuleren",
    delete: "Verwijder",
    edit: "Bewerk",
    close: "Sluiten",
    back: "Terug",
    name: "Naam",
    description: "Omschrijving",
    website: "Website",
    none: "Geen",

    // Colors
    zwart: "Zwart", wit: "Wit", grijs: "Grijs", zilver: "Zilver", rood: "Rood", blauw: "Blauw", 
    groen: "Groen", geel: "Geel", oranje: "Oranje", paars: "Paars", roze: "Roze", goud: "Goud", 
    brons: "Brons", transparant: "Transparant", naturel: "Naturel", "glow in the dark": "Glow in the Dark", regenboog: "Regenboog"
  },
  en: {
    dashboard: "Dashboard",
    inventory: "Inventory",
    printHistory: "Print History",
    printers: "Printers",
    shopping: "Shopping List",
    printPreview: "Print Preview",
    showcaseTitle: "Showcase",
    supportTitle: "Support Project",
    settings: "Settings",
    admin: "Admin Panel",
    menu: "Menu",
    menuManagement: "Management",
    menuTools: "Tools",
    menuPremium: "Premium",
    becomePro: "Become PRO",
    userRatingText: "Users rate us with a",
    madeBy: "Made by",
    notifications: "Notifications",

    tabGeneral: "General",
    tabNotifications: "Notifications",
    tabManagement: "Management",
    tabAccount: "Account",
    tabPro: "PRO",
    appearance: "Appearance",
    winterEdition: "Winter Edition",
    winterEditionDesc: "Snowflakes on the dashboard",
    language: "Language",
    aboutApp: "About the App",
    help: "Help & Support",
    privacyPolicy: "Privacy Policy",
    donateButton: "Buy me a coffee",
    lowStockWarning: "Low Stock Warning",
    unusedWarning: "Unused Warning",
    days: "days",
    enableUpdateNotifications: "Receive notifications about new versions",
    logout: "Logout",
    tabData: "Data Management",
    backupCreate: "Create Backup",
    backupRestore: "Restore Backup",
    dangerZone: "Danger Zone",
    deleteAccount: "Delete Account",
    deleteAccountDesc: "Permanently remove all your data from our database.",
    cancelDeletion: "Cancel Deletion",
    requestSent: "Request submitted",
    requestCancelled: "Request cancelled",
    confirmCancelDeletion: "Are you sure you want to withdraw the deletion request?",
    proTools: "PRO Calculator Tools",
    proToolsDesc: "Set your rates for automatic cost calculation here.",
    electricityRate: "Electricity Price ($/kWh)",
    hourlyRate: "Hourly Rate / Labor ($/h)",
    profitMargin: "Profit Margin (%)",
    roundToNine: "Round prices to .x9",
    exampleElectricityRate: "e.g. 0.35",
    exampleHourlyRate: "e.g. 2.50",
    proFeatureLocked: "PRO Feature Locked",
    upgradeToUnlock: "Upgrade to PRO to use this",
    locationManager: "Location Manager",
    addLocation: "Add Location",
    supplierManager: "Supplier Manager",
    addSupplier: "Add Supplier",
    optional: "Optional",
    exampleLocation: "e.g. Cabinet A, Shelf 2",
    exampleSupplier: "e.g. Amazon",
    exampleWebsite: "e.g. www.amazon.com",
    confirmBackup: "Are you sure you want to import a backup? Your current data will be overwritten.",

    reasonNotUsing: "I no longer use the app",
    reasonMissingFeatures: "Missing features",
    reasonTooComplicated: "Too complicated",
    reasonOtherApp: "Found another app",
    reasonTechnicalIssues: "Technical issues",
    reasonOther: "Other...",

    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    close: "Close",
    back: "Back",
    name: "Name",
    description: "Description",
    website: "Website",
    none: "None",

    zwart: "Black", wit: "White", grijs: "Grey", zilver: "Silver", rood: "Red", blauw: "Blue", 
    groen: "Green", geel: "Yellow", oranje: "Orange", paars: "Purple", roze: "Pink", goud: "Gold", 
    brons: "Bronze", transparant: "Transparent", naturel: "Natural", "glow in the dark": "Glow in the Dark", regenboog: "Rainbow"
  },
  de: {
    dashboard: "Dashboard",
    inventory: "Inventar",
    printHistory: "Logbuch",
    printers: "Drucker",
    shopping: "Einkaufsliste",
    printPreview: "Druckvorschau",
    showcaseTitle: "Schaukasten",
    supportTitle: "Unterstützen",
    settings: "Einstellungen",
    admin: "Admin",
    menu: "Menü",
    menuManagement: "Verwaltung",
    menuTools: "Werkzeuge",
    menuPremium: "Premium",
    becomePro: "PRO werden",
    userRatingText: "Nutzer bewerten uns mit",
    madeBy: "Erstellt von",
    notifications: "Meldungen",

    tabGeneral: "Allgemein",
    tabNotifications: "Meldungen",
    tabManagement: "Verwaltung",
    tabAccount: "Konto",
    tabPro: "PRO",
    appearance: "Aussehen",
    winterEdition: "Winter-Edition",
    winterEditionDesc: "Schneeflocken auf dem Dashboard",
    language: "Sprache",
    aboutApp: "Über die App",
    help: "Hilfe & Support",
    privacyPolicy: "Datenschutz",
    donateButton: "Kaffee spendieren",
    lowStockWarning: "Niedriger Lagerbestand",
    unusedWarning: "Inaktivitäts-Warnung",
    days: "Tage",
    enableUpdateNotifications: "Benachrichtigungen über neue Versionen",
    logout: "Abmelden",
    tabData: "Datenverwaltung",
    backupCreate: "Backup erstellen",
    backupRestore: "Backup einspielen",
    dangerZone: "Gefahrenzone",
    deleteAccount: "Konto löschen",
    deleteAccountDesc: "Löschen Sie alle Ihre Daten dauerhaft aus unserer Datenbank.",
    cancelDeletion: "Löschung abbrechen",
    requestSent: "Anfrage gesendet",
    requestCancelled: "Anfrage abgebrochen",
    confirmCancelDeletion: "Sind Sie sicher, dass Sie die Löschanfrage zurückziehen möchten?",
    proTools: "PRO Rechner-Tools",
    proToolsDesc: "Stellen Sie hier Ihre Tarife für die Kostenberechnung ein.",
    electricityRate: "Strompreis (€/kWh)",
    hourlyRate: "Stundensatz / Arbeit (€/h)",
    profitMargin: "Gewinnspanne (%)",
    roundToNine: "Preise auf .x9 runden",
    exampleElectricityRate: "z.B. 0.35",
    exampleHourlyRate: "z.B. 2.50",
    proFeatureLocked: "PRO Funktion gesperrt",
    upgradeToUnlock: "Upgrade auf PRO, um dies zu nutzen",
    locationManager: "Standortverwaltung",
    addLocation: "Standort hinzufügen",
    supplierManager: "Lieferantenverwaltung",
    addSupplier: "Lieferant hinzufügen",
    optional: "Optional",
    exampleLocation: "z.B. Schrank A, Fach 2",
    exampleSupplier: "z.B. 3D-Druck Shop",
    exampleWebsite: "z.B. www.3d-shop.de",
    confirmBackup: "Möchten Sie wirklich ein Backup importieren? Ihre aktuellen Daten werden überschrieben.",

    reasonNotUsing: "Ich nutze die App nicht mehr",
    reasonMissingFeatures: "Fehlende Funktionen",
    reasonTooComplicated: "Zu kompliziert",
    reasonOtherApp: "Andere App gefunden",
    reasonTechnicalIssues: "Technische Probleme",
    reasonOther: "Andere...",

    save: "Speichern",
    cancel: "Abbrechen",
    delete: "Löschen",
    edit: "Bearbeiten",
    close: "Schließen",
    back: "Zurück",
    name: "Name",
    description: "Beschreibung",
    website: "Webseite",
    none: "Keine",

    zwart: "Schwarz", wit: "Weiß", grijs: "Grau", zilver: "Silber", rood: "Rot", blauw: "Blau", 
    groen: "Grün", geel: "Gelb", oranje: "Orange", paars: "Lila", roze: "Rosa", goud: "Gold", 
    brons: "Bronze", transparant: "Transparent", naturel: "Natur", "glow in the dark": "Glow in the Dark", regenboog: "Regenbogen"
  },
  fr: {
    dashboard: "Tableau de bord",
    inventory: "Inventaire",
    printHistory: "Historique",
    printers: "Imprimantes",
    shopping: "Liste d'achats",
    printPreview: "Aperçu",
    showcaseTitle: "Vitrine",
    supportTitle: "Soutenir le projet",
    settings: "Paramètres",
    admin: "Admin",
    menu: "Menu",
    menuManagement: "Gestion",
    menuTools: "Outils",
    menuPremium: "Premium",
    becomePro: "Devenir PRO",
    userRatingText: "Les utilisateurs nous notent",
    madeBy: "Fait par",
    notifications: "Notifications",

    tabGeneral: "Général",
    tabNotifications: "Notifications",
    tabManagement: "Gestion",
    tabAccount: "Compte",
    tabPro: "PRO",
    appearance: "Apparence",
    winterEdition: "Édition Hiver",
    winterEditionDesc: "Flocons de neige sur le tableau de bord",
    language: "Langue",
    aboutApp: "À propos de l'app",
    help: "Aide & Support",
    privacyPolicy: "Confidentialité",
    donateButton: "Achetez-moi un café",
    lowStockWarning: "Alerte stock bas",
    unusedWarning: "Alerte inactivité",
    days: "jours",
    enableUpdateNotifications: "Notifications pour les nouvelles versions",
    logout: "Déconnexion",
    tabData: "Gestion des données",
    backupCreate: "Créer une sauvegarde",
    backupRestore: "Restaurer une sauvegarde",
    dangerZone: "Zone de danger",
    deleteAccount: "Supprimer le compte",
    deleteAccountDesc: "Supprimez définitivement toutes vos données de notre base.",
    cancelDeletion: "Annuler la suppression",
    requestSent: "Demande soumise",
    requestCancelled: "Demande annulée",
    confirmCancelDeletion: "Êtes-vous sûr de vouloir annuler la demande ?",
    proTools: "Outils PRO Calculator",
    proToolsDesc: "Configurez vos tarifs pour le calcul automatique des coûts.",
    electricityRate: "Prix électricité (€/kWh)",
    hourlyRate: "Tarif horaire / Main d'œuvre (€/h)",
    profitMargin: "Marge bénéficiaire (%)",
    roundToNine: "Arrondir les prix à .x9",
    exampleElectricityRate: "ex. 0.35",
    exampleHourlyRate: "ex. 2.50",
    proFeatureLocked: "Fonction PRO verrouillée",
    upgradeToUnlock: "Passez à PRO pour utiliser ceci",
    locationManager: "Gestion des lieux",
    addLocation: "Ajouter un lieu",
    supplierManager: "Gestion fournisseurs",
    addSupplier: "Ajouter un fournisseur",
    optional: "Optionnel",
    exampleLocation: "ex. Armoire A, Étagère 2",
    exampleSupplier: "ex. Amazon",
    exampleWebsite: "ex. www.amazon.fr",
    confirmBackup: "Voulez-vous vraiment importer une sauvegarde ? Vos données actuelles seront écrasées.",

    reasonNotUsing: "Je n'utilise plus l'app",
    reasonMissingFeatures: "Fonctionnalités manquantes",
    reasonTooComplicated: "Trop compliqué",
    reasonOtherApp: "J'ai trouvé une autre app",
    reasonTechnicalIssues: "Problèmes techniques",
    reasonOther: "Autre...",

    save: "Enregistrer",
    cancel: "Annuler",
    delete: "Supprimer",
    edit: "Modifier",
    close: "Fermer",
    back: "Retour",
    name: "Nom",
    description: "Description",
    website: "Site Web",
    none: "Aucun",

    zwart: "Noir", wit: "Blanc", grijs: "Gris", zilver: "Argent", rood: "Rouge", blauw: "Bleu", 
    groen: "Vert", geel: "Jaune", oranje: "Orange", paars: "Violet", roze: "Rose", goud: "Or", 
    brons: "Bronze", transparant: "Transparent", naturel: "Naturel", "glow in the dark": "Fluorescent", regenboog: "Arc-en-ciel"
  },
  es: {
    dashboard: "Panel",
    inventory: "Inventario",
    printHistory: "Historial",
    printers: "Impresoras",
    shopping: "Lista de compras",
    printPreview: "Vista previa",
    showcaseTitle: "Vitrina",
    supportTitle: "Apoyar proyecto",
    settings: "Ajustes",
    admin: "Admin",
    menu: "Menú",
    menuManagement: "Gestión",
    menuTools: "Herramientas",
    menuPremium: "Premium",
    becomePro: "Hacerse PRO",
    userRatingText: "Los usuarios nos califican con",
    madeBy: "Hecho por",
    notifications: "Notificaciones",

    tabGeneral: "General",
    tabNotifications: "Notificaciones",
    tabManagement: "Gestión",
    tabAccount: "Cuenta",
    tabPro: "PRO",
    appearance: "Apariencia",
    winterEdition: "Edición de Invierno",
    winterEditionDesc: "Copos de nieve en el panel",
    language: "Idioma",
    aboutApp: "Sobre la App",
    help: "Ayuda y Soporte",
    privacyPolicy: "Privacidad",
    donateButton: "Cómprame un café",
    lowStockWarning: "Aviso de stock bajo",
    unusedWarning: "Aviso de inactividad",
    days: "días",
    enableUpdateNotifications: "Notificaciones de nuevas versiones",
    logout: "Cerrar sesión",
    tabData: "Gestión de datos",
    backupCreate: "Crear copia",
    backupRestore: "Restaurar copia",
    dangerZone: "Zona de peligro",
    deleteAccount: "Eliminar cuenta",
    deleteAccountDesc: "Elimina permanentemente todos tus datos de nuestra base.",
    cancelDeletion: "Cancelar eliminación",
    requestSent: "Solicitud enviada",
    requestCancelled: "Solicitud cancelada",
    confirmCancelDeletion: "¿Estás seguro de cancelar la solicitud ?",
    proTools: "Herramientas PRO Calculator",
    proToolsDesc: "Configura tus tarifas para el cálculo de costes.",
    electricityRate: "Precio electricidad (€/kWh)",
    hourlyRate: "Tarifa por hora / Mano de obra (€/h)",
    profitMargin: "Margen de beneficio (%)",
    roundToNine: "Redondear precios a .x9",
    exampleElectricityRate: "ej. 0.35",
    exampleHourlyRate: "ej. 2.50",
    proFeatureLocked: "Función PRO bloqueada",
    upgradeToUnlock: "Pásate a PRO para usar esto",
    locationManager: "Gestión de ubicaciones",
    addLocation: "Añadir ubicación",
    supplierManager: "Gestión proveedores",
    addSupplier: "Añadir proveedor",
    optional: "Opcional",
    exampleLocation: "ej. Armario A, Estante 2",
    exampleSupplier: "ej. Amazon",
    exampleWebsite: "ej. www.amazon.es",
    confirmBackup: "¿Deseas importar una copia? Se sobrescribirán tus datos actuales.",

    reasonNotUsing: "Ya no uso la app",
    reasonMissingFeatures: "Faltan funciones",
    reasonTooComplicated: "Demasiado complicada",
    reasonOtherApp: "He encontrado otra app",
    reasonTechnicalIssues: "Problemas técnicos",
    reasonOther: "Otro...",

    save: "Guardar",
    cancel: "Cancelar",
    delete: "Eliminar",
    edit: "Editar",
    close: "Cerrar",
    back: "Volver",
    name: "Nombre",
    description: "Descripción",
    website: "Sitio web",
    none: "Ninguna",

    zwart: "Negro", wit: "Blanco", grijs: "Gris", zilver: "Plata", rood: "Rojo", blauw: "Azul", 
    groen: "Verde", geel: "Amarillo", oranje: "Naranja", paars: "Morado", roze: "Rosa", goud: "Oro", 
    brons: "Bronce", transparant: "Transparente", naturel: "Natural", "glow in the dark": "Fluorescente", regenboog: "Arcoíris"
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  tColor: (color: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    return (localStorage.getItem('app_language') as Language) || 'nl';
  });

  useEffect(() => {
    localStorage.setItem('app_language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    if (!key) return '';
    return translations[language][key] || translations['en'][key] || key;
  };

  const tColor = (color: string): string => {
    if (!color) return '';
    const lowerColor = color.toLowerCase();
    return translations[language][lowerColor] || translations['en'][lowerColor] || color;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, tColor }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
