
import React, { useState, useEffect, useRef, useMemo } from 'react';
import { Upload, Save, ZoomIn, ZoomOut, Image as ImageIcon, CheckCircle2, AlertCircle, MessageSquare, Trash2, UserX, Database, Copy, RefreshCw, LayoutGrid, Weight, Tag, Layers, Plus, Server, Check, Activity, HardDrive, Shield, Share2, Square, CheckSquare, Users, Clock, Mail, Crown, ToggleLeft, ToggleRight, Loader2, X, Globe, Smartphone, Zap, Star, Sparkles, Disc, AlertTriangle, Eye, EyeOff, BarChart3, PieChart as PieChartIcon, TrendingUp, Box, ChevronRight, LogOut, ArrowLeft, History, Edit2, ClipboardList, ListPlus } from 'lucide-react';
import { PieChart, Pie, Cell, ResponsiveContainer, Tooltip, BarChart, Bar, XAxis, YAxis, CartesianGrid } from 'recharts';
import { supabase } from '../services/supabase';
import { useLogo } from '../contexts/LogoContext';
import { useLanguage } from '../contexts/LanguageContext';
import { parseCatalogText } from '../services/geminiService';

type AdminTab = 'dashboard' | 'users' | 'sql' | 'logo' | 'spools' | 'data' | 'feedback' | 'requests';

const COLORS = ['#3b82f6', '#10b981', '#f59e0b', '#ef4444', '#8b5cf6', '#ec4899', '#06b6d4', '#64748b'];

const MASTER_SQL = `-- 1. SPOEL DATABASE SCHEMA UPDATE
create table if not exists public.spool_weights (
  id bigint generated by default as identity primary key,
  weight numeric,
  name text
);

-- Zorg dat 'name' niet verplicht is (voor compatibiliteit)
alter table public.spool_weights alter column name drop not null;

-- Forceer kolommen als ze nog niet bestaan
do $$ 
begin 
  if not exists (select 1 from information_schema.columns where table_name='spool_weights' and column_name='brand') then
    alter table public.spool_weights add column brand text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name='spool_weights' and column_name='size') then
    alter table public.spool_weights add column size text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name='spool_weights' and column_name='spool_material') then
    alter table public.spool_weights add column spool_material text;
  end if;
end $$;

alter table public.spool_weights enable row level security;
drop policy if exists "Public read access" on public.spool_weights;
create policy "Public read access" on public.spool_weights for select using (true);
drop policy if exists "Admins manage spools" on public.spool_weights;
create policy "Admins manage spools" on public.spool_weights for all using (true);

-- 2. ANDERE TABELLEN & POLICIES
create table if not exists public.brands (id bigint generated by default as identity primary key, name text unique);
create table if not exists public.materials (id bigint generated by default as identity primary key, name text unique);
create table if not exists public.global_settings (key text primary key, value text);

alter table public.brands enable row level security;
alter table public.materials enable row level security;
alter table public.global_settings enable row level security;

drop policy if exists "Public read access brands" on public.brands;
create policy "Public read access brands" on public.brands for select using (true);
drop policy if exists "Public read access materials" on public.materials;
create policy "Public read access materials" on public.materials for select using (true);
drop policy if exists "Public read access global" on public.global_settings;
create policy "Public read access global" on public.global_settings for select using (true);

drop policy if exists "Admins manage all" on public.brands;
create policy "Admins manage all" on public.brands for all using (true);
drop policy if exists "Admins manage all mat" on public.materials;
create policy "Admins manage all mat" on public.materials for all using (true);
drop policy if exists "Admins manage all glob" on public.global_settings;
create policy "Admins manage all glob" on public.global_settings for all using (true);
`;

interface AdminPanelProps {
  onClose?: () => void;
}

export const AdminPanel: React.FC<AdminPanelProps> = ({ onClose }) => {
  const { refreshLogo, logoUrl: currentAppLogo } = useLogo();
  const { t } = useLanguage();
  const [activeTab, setActiveTab] = useState<AdminTab>('dashboard');
  const [logoFile, setLogoFile] = useState<File | null>(null);
  const [previewUrl, setPreviewUrl] = useState<string | null>(null);
  const [isUploading, setIsUploading] = useState(false);
  const [logoStatus, setLogoStatus] = useState<'idle' | 'success' | 'error'>('idle');
  const [logoMsg, setLogoMsg] = useState('');
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [feedbacks, setFeedbacks] = useState<any[]>([]);
  const [requests, setRequests] = useState<any[]>([]);
  const [users, setUsers] = useState<any[]>([]);
  const [spoolWeights, setSpoolWeights] = useState<any[]>([]);
  const [brands, setBrands] = useState<any[]>([]);
  const [materials, setMaterials] = useState<any[]>([]);
  const [tableCounts, setTableCounts] = useState({ logs: 0, filaments: 0, materials: 0, proUsers: 0, totalUsers: 0 });
  const [isLoading, setIsLoading] = useState(false);
  const [updatingUserId, setUpdatingUserId] = useState<string | null>(null);
  const [deletingFeedbackId, setDeletingFeedbackId] = useState<number | null>(null);
  const [latency, setLatency] = useState<number | null>(null);
  const [newSpool, setNewSpool] = useState({ brand: '', size: '1000g', spool_material: 'Plastic', weight: '' });
  const [newBrand, setNewBrand] = useState('');
  const [newMaterial, setNewMaterial] = useState('');
  const [sqlCopied, setSqlCopied] = useState(false);

  // AI Import State
  const [showAiImport, setShowAiImport] = useState(false);
  const [importText, setImportText] = useState('');
  const [isParsingCatalog, setIsParsingCatalog] = useState(false);
  const [parsedSpools, setParsedSpools] = useState<{ brand: string, size: string, spool_material: string, weight: number, selected: boolean }[]>([]);

  // Spool Database Edit State
  const [editingSpoolId, setEditingSpoolId] = useState<number | null>(null);
  const [editingSpoolData, setEditingSpoolData] = useState({ brand: '', size: '', spool_material: '', weight: '' });

  const isAiConfigured = !!process.env.API_KEY && process.env.API_KEY.length > 5;

  useEffect(() => {
    loadDashboardStats();
    checkLatency();
    if (activeTab === 'feedback') loadFeedback();
    if (activeTab === 'requests') loadRequests();
    if (activeTab === 'users') loadUsers();
    if (activeTab === 'spools') loadSpoolWeights();
    if (activeTab === 'data') { loadBrands(); loadMaterials(); }
  }, [activeTab]);

  const checkLatency = async () => {
     const start = performance.now();
     try {
       await supabase.from('filaments').select('id').limit(1);
       const end = performance.now();
       setLatency(Math.round(end - start));
     } catch (e) {
       setLatency(null);
     }
  };

  const loadDashboardStats = async () => {
     try {
        const { count: lCount } = await supabase.from('print_jobs').select('*', { count: 'exact', head: true }); 
        const { count: fCount } = await supabase.from('filaments').select('*', { count: 'exact', head: true });
        const { count: mCount } = await supabase.from('other_materials').select('*', { count: 'exact', head: true });
        const { count: uCount } = await supabase.from('profiles').select('*', { count: 'exact', head: true });
        const { count: pCount } = await supabase.from('profiles').select('*', { count: 'exact', head: true }).eq('is_pro', true);

        setTableCounts({ 
           logs: lCount || 0, 
           filaments: fCount || 0, 
           materials: mCount || 0,
           totalUsers: uCount || 0,
           proUsers: pCount || 0
        });
     } catch (e) {
        console.error("Stats load failed", e);
     }
  };

  const handleCopySql = async () => {
    await navigator.clipboard.writeText(MASTER_SQL);
    setSqlCopied(true);
    setTimeout(() => setSqlCopied(false), 2000);
  };

  const loadUsers = async () => {
    setIsLoading(true);
    try {
      const { data, error } = await supabase.from('profiles').select('id, email, is_pro, created_at').order('created_at', { ascending: false });
      if (error) throw error;
      setUsers(data || []);
    } catch (e: any) { alert(e.message); } finally { setIsLoading(false); }
  };

  const toggleProStatus = async (userId: string, currentStatus: boolean) => {
    setUpdatingUserId(userId);
    try {
      const { error } = await supabase.from('profiles').upsert({ id: userId, is_pro: !currentStatus }, { onConflict: 'id' });
      if (error) throw error;
      setUsers(prev => prev.map(u => u.id === userId ? { ...u, is_pro: !currentStatus } : u));
      loadDashboardStats();
    } catch (e: any) { alert(e.message); } finally { setUpdatingUserId(null); }
  };

  const handleLogoUpload = async () => {
    if (!previewUrl) return;
    setIsUploading(true);
    try {
      const { error } = await supabase.from('global_settings').upsert({ key: 'app_logo', value: previewUrl });
      if (error) throw error;
      setLogoStatus('success');
      setLogoMsg('Logo succesvol bijgewerkt!');
      await refreshLogo();
    } catch (e: any) { setLogoStatus('error'); setLogoMsg(e.message); } finally { setIsUploading(false); }
  };

  const loadFeedback = async () => { 
    setIsLoading(true); 
    const { data } = await supabase.from('feedback').select('*').order('created_at', { ascending: false }); 
    if (data) setFeedbacks(data); 
    setIsLoading(false); 
  };

  const toggleFeedbackRead = async (id: number, currentStatus: boolean) => {
    try {
      await supabase.from('feedback').update({ is_read: !currentStatus }).eq('id', id);
      setFeedbacks(prev => prev.map(f => f.id === id ? { ...f, is_read: !currentStatus } : f));
    } catch (e: any) { alert(e.message); }
  };

  const deleteFeedback = async (id: number) => {
    if (!confirm("Feedback verwijderen?")) return;
    setDeletingFeedbackId(id);
    try {
       await supabase.from('feedback').delete().eq('id', id);
       setFeedbacks(prev => prev.filter(f => f.id !== id));
    } catch (e: any) { alert(e.message); } finally { setDeletingFeedbackId(null); }
  };
  
  const loadRequests = async () => { 
    setIsLoading(true); 
    const { data } = await supabase.from('deletion_requests').select('*').order('created_at', { ascending: false }); 
    if (data) setRequests(data); 
    setIsLoading(false); 
  };

  const loadSpoolWeights = async () => { setIsLoading(true); const { data } = await supabase.from('spool_weights').select('*').order('brand', { ascending: true }); if (data) setSpoolWeights(data); setIsLoading(false); };
  const loadBrands = async () => { const { data } = await supabase.from('brands').select('*').order('name'); if (data) setBrands(data || []); };
  const loadMaterials = async () => { const { data } = await supabase.from('materials').select('*').order('name'); if (data) setMaterials(data || []); };

  const handleAddSpool = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!newSpool.brand || !newSpool.weight) return;
    try {
       await supabase.from('spool_weights').insert({ 
         brand: newSpool.brand, 
         size: newSpool.size, 
         spool_material: newSpool.spool_material, 
         weight: Number(newSpool.weight),
         name: `${newSpool.brand} (${newSpool.size})` // Vul de oude 'name' kolom voor compatibiliteit
       });
       setNewSpool({ brand: '', size: '1000g', spool_material: 'Plastic', weight: '' });
       loadSpoolWeights();
    } catch (e: any) { alert(e.message); }
  };

  const handleUpdateSpool = async (id: number) => {
    if (!editingSpoolData.brand || !editingSpoolData.weight) return;
    try {
       await supabase.from('spool_weights').update({ 
         brand: editingSpoolData.brand, 
         size: editingSpoolData.size, 
         spool_material: editingSpoolData.spool_material, 
         weight: Number(editingSpoolData.weight),
         name: `${editingSpoolData.brand} (${editingSpoolData.size})`
       }).eq('id', id);
       setEditingSpoolId(null);
       loadSpoolWeights();
    } catch (e: any) { alert(e.message); }
  };

  const handleDeleteSpool = async (id: number) => {
    if (!confirm("Zeker weten?")) return;
    try {
       await supabase.from('spool_weights').delete().eq('id', id);
       loadSpoolWeights();
    } catch (e: any) { alert(e.message); }
  };

  const handleAiCatalogParse = async () => {
     if (!importText.trim()) return;
     setIsParsingCatalog(true);
     try {
        const results = await parseCatalogText(importText);
        setParsedSpools(results.map(r => ({ ...r, selected: true })));
     } catch (e: any) { alert("Analyse mislukt."); } finally { setIsParsingCatalog(false); }
  };

  const handleBulkImport = async () => {
     const toImport = parsedSpools.filter(s => s.selected);
     if (toImport.length === 0) return;
     setIsLoading(true);
     try {
        const payload = toImport.map(({ brand, size, spool_material, weight }) => ({ 
          brand, 
          size, 
          spool_material, 
          weight,
          name: `${brand} (${size})`
        }));
        const { error } = await supabase.from('spool_weights').insert(payload);
        if (error) throw error;
        setShowAiImport(false);
        setImportText('');
        setParsedSpools([]);
        loadSpoolWeights();
     } catch (e: any) { alert(e.message); } finally { setIsLoading(false); }
  };

  const startEditingSpool = (s: any) => {
     setEditingSpoolId(s.id);
     setEditingSpoolData({ brand: s.brand || '', size: s.size || '1000g', spool_material: s.spool_material || 'Plastic', weight: s.weight.toString() });
  };

  return (
    <div className="max-w-7xl mx-auto pb-20 animate-fade-in flex flex-col gap-8">
       <div className="space-y-6 w-full">
          <div className="bg-white dark:bg-slate-800 rounded-2xl shadow-sm border border-slate-200 dark:border-slate-700 p-2 flex items-center overflow-x-auto gap-2 scrollbar-hide text-white">
             <button onClick={() => setActiveTab('dashboard')} className={`flex items-center gap-2 px-5 py-2.5 rounded-xl text-sm font-bold whitespace-nowrap transition-colors ${activeTab === 'dashboard' ? 'bg-slate-100 dark:bg-slate-700 text-slate-800 dark:white' : 'text-slate-500 hover:bg-slate-50 dark:hover:bg-slate-900'}`}><LayoutGrid size={18}/> Dashboard</button>
             <button onClick={() => setActiveTab('users')} className={`flex items-center gap-2 px-5 py-2.5 rounded-xl text-sm font-bold whitespace-nowrap transition-colors ${activeTab === 'users' ? 'bg-blue-100 dark:bg-blue-900/30 text-blue-600 dark:text-blue-400' : 'text-slate-500 hover:bg-slate-50 dark:hover:bg-slate-900'}`}><Users size={18}/> Gebruikers</button>
             <button onClick={() => setActiveTab('spools')} className={`flex items-center gap-2 px-5 py-2.5 rounded-xl text-sm font-bold whitespace-nowrap transition-colors ${activeTab === 'spools' ? 'bg-emerald-100 dark:bg-emerald-900/30 text-emerald-600 dark:text-emerald-400' : 'text-slate-500 hover:bg-slate-50 dark:hover:bg-slate-900'}`}><Disc size={18}/> Spoel Database</button>
             <button onClick={() => setActiveTab('data')} className={`flex items-center gap-2 px-5 py-2.5 rounded-xl text-sm font-bold whitespace-nowrap transition-colors ${activeTab === 'data' ? 'bg-amber-100 dark:bg-amber-900/30 text-amber-600 dark:text-amber-400' : 'text-slate-500 hover:bg-slate-50 dark:hover:bg-slate-900'}`}><Tag size={18}/> Merken & Materialen</button>
             <button onClick={() => setActiveTab('logo')} className={`flex items-center gap-2 px-5 py-2.5 rounded-xl text-sm font-bold whitespace-nowrap transition-colors ${activeTab === 'logo' ? 'bg-indigo-100 dark:bg-indigo-900/30 text-indigo-600 dark:text-indigo-400' : 'text-slate-500 hover:bg-slate-50 dark:hover:bg-slate-900'}`}><ImageIcon size={18}/> Logo</button>
             <button onClick={() => setActiveTab('feedback')} className={`flex items-center gap-2 px-5 py-2.5 rounded-xl text-sm font-bold whitespace-nowrap transition-colors ${activeTab === 'feedback' ? 'bg-purple-100 dark:bg-purple-900/30 text-purple-600 dark:text-purple-400' : 'text-slate-500 hover:bg-slate-50 dark:hover:bg-slate-900'}`}><MessageSquare size={18}/> Feedback</button>
          </div>

          <div className="min-h-[400px]">
             {activeTab === 'dashboard' && (
                <div className="space-y-6">
                   <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-4">
                      <div className="bg-white dark:bg-slate-800 p-6 rounded-2xl border border-slate-200 dark:border-slate-700 shadow-sm">
                         <h3 className="text-slate-500 text-[10px] font-black uppercase tracking-widest mb-1">Gebruikers</h3>
                         <p className="text-3xl font-black text-slate-800 dark:text-white">{tableCounts.totalUsers}</p>
                      </div>
                      <div className="bg-white dark:bg-slate-800 p-6 rounded-2xl border border-slate-200 dark:border-slate-700 shadow-sm">
                         <h3 className="text-slate-500 text-[10px] font-black uppercase tracking-widest mb-1">PRO Leden</h3>
                         <p className="text-3xl font-black text-amber-500">{tableCounts.proUsers}</p>
                      </div>
                      <div className="bg-white dark:bg-slate-800 p-6 rounded-2xl border border-slate-200 dark:border-slate-700 shadow-sm">
                         <h3 className="text-slate-500 text-[10px] font-black uppercase tracking-widest mb-1">Filamenten</h3>
                         <p className="text-3xl font-black text-slate-800 dark:text-white">{tableCounts.filaments}</p>
                      </div>
                      <div className="bg-white dark:bg-slate-800 p-6 rounded-2xl border border-slate-200 dark:border-slate-700 shadow-sm">
                         <h3 className="text-slate-500 text-[10px] font-black uppercase tracking-widest mb-1">Andere Mat.</h3>
                         <p className="text-3xl font-black text-slate-800 dark:text-white">{tableCounts.materials}</p>
                      </div>
                      <div className="bg-white dark:bg-slate-800 p-6 rounded-2xl border border-slate-200 dark:border-slate-700 shadow-sm">
                         <h3 className="text-slate-500 text-[10px] font-black uppercase tracking-widest mb-1">Open Feedback</h3>
                         <p className="text-3xl font-black text-purple-600">{feedbacks.filter(f => !f.is_read).length}</p>
                      </div>
                   </div>

                   <div className="bg-white dark:bg-slate-800 p-8 rounded-3xl border border-slate-200 dark:border-slate-700 shadow-sm flex flex-col md:flex-row items-center justify-between gap-6">
                      <div className="flex-1">
                         <h3 className="text-xl font-bold text-slate-800 dark:text-white flex items-center gap-2 mb-2"><Database className="text-blue-500"/> Database Setup</h3>
                         <p className="text-slate-500 text-sm">Kopieer de volledige SQL code om alle tabellen en RLS policies in één keer correct aan te maken of te updaten in Supabase.</p>
                      </div>
                      <button onClick={handleCopySql} className={`px-8 py-4 rounded-2xl font-black transition-all flex items-center gap-2 shadow-lg ${sqlCopied ? 'bg-emerald-500 text-white' : 'bg-blue-600 hover:bg-blue-500 text-white'}`}>
                         {sqlCopied ? <Check/> : <Copy/>} {sqlCopied ? 'Gekopieerd!' : 'SQL Kopiëren'}
                      </button>
                   </div>
                </div>
             )}

             {activeTab === 'users' && (
                <div className="bg-white dark:bg-slate-800 rounded-2xl border border-slate-200 dark:border-slate-700 shadow-sm overflow-hidden">
                   <div className="p-6 border-b border-slate-100 dark:border-slate-700 bg-slate-50 dark:bg-slate-900/50 flex justify-between items-center">
                      <h3 className="font-bold text-slate-800 dark:text-white flex items-center gap-3"><Users size={20}/> Gebruikers Lijst</h3>
                      <button onClick={loadUsers} className="p-2 hover:bg-slate-200 dark:hover:bg-slate-700 rounded-lg transition-colors"><RefreshCw size={18} className={isLoading ? 'animate-spin' : ''}/></button>
                   </div>
                   <div className="overflow-x-auto">
                      <table className="w-full text-left">
                         <thead className="bg-slate-50 dark:bg-slate-900">
                            <tr>
                               <th className="p-4 text-[10px] font-black text-slate-500 uppercase">E-mail</th>
                               <th className="p-4 text-[10px] font-black text-slate-500 uppercase text-center">PRO Status</th>
                               <th className="p-4 text-[10px] font-black text-slate-500 uppercase text-right">Registratie</th>
                            </tr>
                         </thead>
                         <tbody className="divide-y divide-slate-100 dark:divide-slate-700">
                            {users.map(u => (
                               <tr key={u.id}>
                                  <td className="p-4 text-sm font-bold dark:text-white">{u.email}</td>
                                  <td className="p-4 text-center">
                                     <button onClick={() => toggleProStatus(u.id, u.is_pro)} disabled={updatingUserId === u.id} className={`px-4 py-1.5 rounded-full text-[10px] font-black uppercase transition-all ${u.is_pro ? 'bg-amber-100 text-amber-700 border border-amber-200' : 'bg-slate-100 text-slate-500 border border-slate-200'}`}>
                                        {updatingUserId === u.id ? <Loader2 size={12} className="animate-spin"/> : u.is_pro ? 'PRO Lid' : 'Maak PRO'}
                                     </button>
                                  </td>
                                  <td className="p-4 text-right text-xs text-slate-400">{new Date(u.created_at).toLocaleDateString()}</td>
                               </tr>
                            ))}
                         </tbody>
                      </table>
                   </div>
                </div>
             )}

             {activeTab === 'spools' && (
                <div className="space-y-6">
                   <div className="bg-white dark:bg-slate-800 p-6 rounded-2xl border border-slate-200 dark:border-slate-700 shadow-sm flex flex-col gap-6">
                      <div className="flex justify-between items-center">
                         <h3 className="font-bold text-slate-800 dark:text-white flex items-center gap-2"><Plus size={20} className="text-emerald-500"/> Handmatig Toevoegen</h3>
                         <button onClick={() => setShowAiImport(!showAiImport)} className="bg-indigo-600 hover:bg-indigo-500 text-white font-bold px-6 py-2.5 rounded-xl flex items-center gap-2 transition-all active:scale-95"><Sparkles size={18} /> AI Import</button>
                      </div>
                      <form onSubmit={handleAddSpool} className="grid grid-cols-1 md:grid-cols-5 gap-3">
                         <div className="md:col-span-2"><label className="text-[10px] font-black uppercase text-slate-500 mb-1 block">Merk</label><input type="text" value={newSpool.brand} onChange={e => setNewSpool({...newSpool, brand: e.target.value})} placeholder="bv. Bambu Lab" className="w-full bg-slate-50 dark:bg-slate-800 border border-slate-300 dark:border-slate-700 rounded-xl p-3 outline-none focus:ring-2 focus:ring-blue-500 dark:text-white" /></div>
                         <div><label className="text-[10px] font-black uppercase text-slate-500 mb-1 block">Grootte</label><input type="text" value={newSpool.size} onChange={e => setNewSpool({...newSpool, size: e.target.value})} placeholder="bv. 1000g" className="w-full bg-slate-50 dark:bg-slate-800 border border-slate-300 dark:border-slate-700 rounded-xl p-3 outline-none focus:ring-2 focus:ring-blue-500 dark:text-white" /></div>
                         <div><label className="text-[10px] font-black uppercase text-slate-500 mb-1 block">Materiaal</label><input type="text" value={newSpool.spool_material} onChange={e => setNewSpool({...newSpool, spool_material: e.target.value})} placeholder="bv. Plastic" className="w-full bg-slate-50 dark:bg-slate-800 border border-slate-300 dark:border-slate-700 rounded-xl p-3 outline-none focus:ring-2 focus:ring-blue-500 dark:text-white" /></div>
                         <div className="relative"><label className="text-[10px] font-black uppercase text-slate-500 mb-1 block">Leeg gewicht</label><input type="number" value={newSpool.weight} onChange={e => setNewSpool({...newSpool, weight: e.target.value})} className="w-full bg-slate-50 dark:bg-slate-800 border border-slate-300 dark:border-slate-700 rounded-xl p-3 outline-none focus:ring-2 focus:ring-blue-500 dark:text-white" /><span className="absolute right-3 top-9 text-slate-400 text-xs">g</span></div>
                         <div className="md:col-span-5 pt-2"><button type="submit" className="w-full bg-emerald-600 hover:bg-emerald-500 text-white font-bold py-3 rounded-xl transition-all shadow-md">Toevoegen aan Database</button></div>
                      </form>
                   </div>

                   {showAiImport && (
                      <div className="bg-indigo-50 dark:bg-indigo-900/10 rounded-2xl border border-indigo-200 p-6 animate-fade-in space-y-4">
                         <div className="flex justify-between items-center"><h3 className="font-bold text-indigo-900 dark:text-indigo-400">AI Catalogus Import</h3><button onClick={() => setShowAiImport(false)}><X size={20}/></button></div>
                         {!parsedSpools.length ? (
                            <div className="space-y-4">
                               <textarea value={importText} onChange={e => setImportText(e.target.value)} placeholder="Plak tekst van Printables/catalogus hier..." className="w-full h-48 bg-white dark:bg-slate-900 border border-indigo-200 rounded-xl p-4 font-mono text-sm" />
                               <button onClick={handleAiCatalogParse} disabled={isParsingCatalog || !importText.trim()} className="w-full py-4 bg-indigo-600 text-white font-black rounded-xl shadow-lg transition-all flex items-center justify-center gap-2">{isParsingCatalog ? <Loader2 className="animate-spin" /> : 'Analyseer met AI'}</button>
                            </div>
                         ) : (
                            <div className="space-y-4">
                               <div className="flex justify-between items-center"><span className="text-sm font-bold">{parsedSpools.length} gevonden</span><div className="flex gap-2"><button onClick={() => setParsedSpools([])} className="px-4 py-2 text-xs bg-slate-100 rounded-lg">Reset</button><button onClick={handleBulkImport} className="px-4 py-2 text-xs bg-green-600 text-white rounded-lg">Bulk Import ({parsedSpools.filter(s=>s.selected).length})</button></div></div>
                               <div className="max-h-[300px] overflow-y-auto space-y-2">
                                  {parsedSpools.map((s, idx) => (
                                     <div key={idx} className="bg-white dark:bg-slate-900 p-3 rounded-xl border border-slate-200 flex items-center justify-between">
                                        <div className="flex items-center gap-3"><input type="checkbox" checked={s.selected} onChange={() => { const next = [...parsedSpools]; next[idx].selected = !next[idx].selected; setParsedSpools(next); }} className="w-5 h-5 accent-indigo-600" /><div className="text-sm"><span className="font-bold dark:text-white">{s.brand}</span><span className="text-slate-400 ml-2">{s.size} • {s.spool_material}</span></div></div>
                                        <span className="text-sm font-black text-indigo-600">{s.weight}g</span>
                                     </div>
                                  ))}
                               </div>
                            </div>
                         )}
                      </div>
                   )}

                   <div className="bg-white dark:bg-slate-800 rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
                      <div className="max-h-[600px] overflow-y-auto">
                         <table className="w-full text-left">
                            <thead className="bg-slate-50 dark:bg-slate-900 sticky top-0 z-10">
                               <tr>
                                  <th className="p-4 text-[10px] font-black text-slate-500 uppercase tracking-widest">Merk</th>
                                  <th className="p-4 text-[10px] font-black text-slate-500 uppercase tracking-widest">Grootte</th>
                                  <th className="p-4 text-[10px] font-black text-slate-500 uppercase tracking-widest">Materiaal</th>
                                  <th className="p-4 text-[10px] font-black text-slate-500 uppercase tracking-widest text-center">Gewicht</th>
                                  <th className="p-4 text-[10px] font-black text-slate-500 uppercase tracking-widest text-right">Actie</th>
                               </tr>
                            </thead>
                            <tbody className="divide-y divide-slate-100 dark:divide-slate-700">
                               {spoolWeights.map(s => (
                                  <tr key={s.id} className="hover:bg-slate-50 dark:hover:bg-slate-800/30">
                                     <td className="p-4 font-bold dark:text-white">{editingSpoolId === s.id ? <input type="text" value={editingSpoolData.brand} onChange={e => setEditingSpoolData({...editingSpoolData, brand: e.target.value})} className="w-full bg-white dark:bg-slate-900 border border-emerald-500 rounded p-1 outline-none text-sm" /> : (s.brand || s.name || '---')}</td>
                                     <td className="p-4 text-sm text-slate-600 dark:text-slate-400">{editingSpoolId === s.id ? <input type="text" value={editingSpoolData.size} onChange={e => setEditingSpoolData({...editingSpoolData, size: e.target.value})} className="w-full bg-white dark:bg-slate-900 border border-emerald-500 rounded p-1 outline-none text-sm" /> : (s.size || '---')}</td>
                                     <td className="p-4 text-sm text-slate-600 dark:text-slate-400">{editingSpoolId === s.id ? <input type="text" value={editingSpoolData.spool_material} onChange={e => setEditingSpoolData({...editingSpoolData, spool_material: e.target.value})} className="w-full bg-white dark:bg-slate-900 border border-emerald-500 rounded p-1 outline-none text-sm" /> : (s.spool_material || '---')}</td>
                                     <td className="p-4 text-center">{editingSpoolId === s.id ? <input type="number" value={editingSpoolData.weight} onChange={e => setEditingSpoolData({...editingSpoolData, weight: e.target.value})} className="w-20 bg-white dark:bg-slate-900 border border-emerald-500 rounded p-1 text-center" /> : <span className="font-bold text-emerald-600 dark:text-emerald-400">{s.weight}g</span>}</td>
                                     <td className="p-4 text-right">
                                        {editingSpoolId === s.id ? (
                                           <div className="flex justify-end gap-2"><button onClick={() => handleUpdateSpool(s.id)} className="text-emerald-600"><Save size={18}/></button><button onClick={() => setEditingSpoolId(null)} className="text-slate-400"><X size={18}/></button></div>
                                        ) : (
                                           <div className="flex justify-end gap-2"><button onClick={() => startEditingSpool(s)} className="text-slate-400 hover:text-blue-500 transition-colors"><Edit2 size={18}/></button><button onClick={() => handleDeleteSpool(s.id)} className="text-slate-400 hover:text-red-500 transition-colors"><Trash2 size={18}/></button></div>
                                        )}
                                     </td>
                                  </tr>
                               ))}
                            </tbody>
                         </table>
                      </div>
                   </div>
                </div>
             )}

             {activeTab === 'feedback' && (
                <div className="bg-white dark:bg-slate-800 rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
                   <div className="p-6 border-b bg-slate-50 dark:bg-slate-900/50 flex justify-between items-center"><h3 className="font-bold dark:text-white flex items-center gap-3"><MessageSquare size={20}/> Feedback Lijst</h3></div>
                   <div className="overflow-x-auto">
                      <table className="w-full text-left">
                         <thead className="bg-slate-50 dark:bg-slate-900">
                            <tr>
                               <th className="p-4 text-[10px] font-black text-slate-500 uppercase w-12">Status</th>
                               <th className="p-4 text-[10px] font-black text-slate-500 uppercase">Bericht</th>
                               <th className="p-4 text-[10px] font-black text-slate-500 uppercase text-center">Rating</th>
                               <th className="p-4 text-[10px] font-black text-slate-500 uppercase text-right">Actie</th>
                            </tr>
                         </thead>
                         <tbody className="divide-y divide-slate-100 dark:divide-slate-700">
                            {feedbacks.map(f => (
                               <tr key={f.id} className={!f.is_read ? 'bg-blue-50/20' : ''}>
                                  <td className="p-4 text-center">{f.is_read ? <Eye size={18} className="text-slate-400"/> : <EyeOff size={18} className="text-blue-500"/>}</td>
                                  <td className="p-4 text-sm dark:text-white max-w-lg truncate">{f.message}</td>
                                  <td className="p-4 text-center font-black text-amber-500">{f.rating}/5</td>
                                  <td className="p-4 text-right flex justify-end gap-2">
                                     <button onClick={() => toggleFeedbackRead(f.id, f.is_read)} className="p-2 bg-blue-50 text-blue-600 rounded-lg"><Check size={16}/></button>
                                     <button onClick={() => deleteFeedback(f.id)} className="p-2 bg-red-50 text-red-600 rounded-lg"><Trash2 size={16}/></button>
                                  </td>
                               </tr>
                            ))}
                         </tbody>
                      </table>
                   </div>
                </div>
             )}

             {activeTab === 'logo' && (
                <div className="bg-white dark:bg-slate-800 p-8 rounded-3xl border border-slate-200 shadow-sm flex flex-col items-center">
                   <h3 className="text-xl font-bold mb-6 dark:text-white">Custom App Logo</h3>
                   <div onClick={() => fileInputRef.current?.click()} className="w-48 h-48 bg-slate-50 dark:bg-slate-900 border-2 border-dashed rounded-3xl flex items-center justify-center cursor-pointer overflow-hidden mb-6">
                      {previewUrl ? <img src={previewUrl} className="w-full h-full object-contain p-4" /> : <ImageIcon size={48} className="text-slate-300"/>}
                      <input type="file" ref={fileInputRef} onChange={(e) => { const f = e.target.files?.[0]; if(f) { setLogoFile(f); const r = new FileReader(); r.onloadend = () => setPreviewUrl(r.result as string); r.readAsDataURL(f); } }} className="hidden" accept="image/*" />
                   </div>
                   <button onClick={handleLogoUpload} disabled={!previewUrl || isUploading} className="w-full max-w-xs bg-indigo-600 text-white font-bold py-3 rounded-xl shadow-lg flex items-center justify-center gap-2">{isUploading ? <Loader2 className="animate-spin"/> : <Save/>} Logo Opslaan</button>
                </div>
             )}

             {activeTab === 'data' && (
                <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                   <div className="bg-white dark:bg-slate-800 p-6 rounded-2xl border border-slate-200 shadow-sm">
                      <h3 className="font-bold mb-4 dark:text-white flex items-center gap-2"><Tag size={20}/> Merken</h3>
                      <div className="flex gap-2 mb-4"><input type="text" value={newBrand} onChange={e => setNewBrand(e.target.value)} placeholder="Nieuw merk..." className="flex-1 bg-slate-50 dark:bg-slate-900 p-3 rounded-xl dark:text-white border" /><button onClick={async () => { if(newBrand) { await supabase.from('brands').insert({name: newBrand}); setNewBrand(''); loadBrands(); } }} className="bg-blue-600 text-white px-4 rounded-xl">Voeg toe</button></div>
                      <div className="max-h-96 overflow-y-auto space-y-1">{brands.map(b => <div key={b.id} className="flex justify-between items-center p-3 bg-slate-50 dark:bg-slate-900 rounded-lg"><span className="text-sm dark:text-white">{b.name}</span><button onClick={async () => { if(confirm("Delete?")){ await supabase.from('brands').delete().eq('id', b.id); loadBrands(); } }} className="text-red-400"><Trash2 size={14}/></button></div>)}</div>
                   </div>
                   <div className="bg-white dark:bg-slate-800 p-6 rounded-2xl border border-slate-200 shadow-sm">
                      <h3 className="font-bold mb-4 dark:text-white flex items-center gap-2"><Layers size={20}/> Materialen</h3>
                      <div className="flex gap-2 mb-4"><input type="text" value={newMaterial} onChange={e => setNewMaterial(e.target.value)} placeholder="Nieuw materiaal..." className="flex-1 bg-slate-50 dark:bg-slate-900 p-3 rounded-xl dark:text-white border" /><button onClick={async () => { if(newMaterial) { await supabase.from('materials').insert({name: newMaterial}); setNewMaterial(''); loadMaterials(); } }} className="bg-blue-600 text-white px-4 rounded-xl">Voeg toe</button></div>
                      <div className="max-h-96 overflow-y-auto space-y-1">{materials.map(m => <div key={m.id} className="flex justify-between items-center p-3 bg-slate-50 dark:bg-slate-900 rounded-lg"><span className="text-sm dark:text-white">{m.name}</span><button onClick={async () => { if(confirm("Delete?")){ await supabase.from('materials').delete().eq('id', m.id); loadMaterials(); } }} className="text-red-400"><Trash2 size={14}/></button></div>)}</div>
                   </div>
                </div>
             )}
          </div>
       </div>

       <div className="bg-slate-900 rounded-[32px] p-8 text-white flex flex-wrap gap-8 items-center justify-between border border-slate-800">
          <div className="flex items-center gap-4"><div className="bg-emerald-500/20 p-3 rounded-2xl"><Server className="text-emerald-400" size={32}/></div><div><h4 className="font-black text-xl leading-none">SERVER STATUS</h4><div className="flex items-center gap-2 text-emerald-400 text-sm font-bold mt-1"><span className="w-2 h-2 bg-emerald-400 rounded-full animate-pulse"></span> ONLINE</div></div></div>
          <div className="flex flex-wrap gap-10">
             <div className="flex flex-col"><span className="text-[10px] text-slate-500 font-black uppercase">Database</span><span className="font-bold">Supabase (Frankfurt)</span></div>
             <div className="flex flex-col"><span className="text-[10px] text-slate-500 font-black uppercase">Latency</span><span className="font-bold text-emerald-400">{latency ? `${latency}ms` : '---'}</span></div>
             <div className="flex flex-col"><span className="text-[10px] text-slate-500 font-black uppercase">AI Engine</span><span className={`font-bold ${isAiConfigured ? 'text-emerald-400' : 'text-red-400'}`}>{isAiConfigured ? 'Gemini 3 Flash' : 'Mist Key'}</span></div>
             <div className="flex flex-col"><span className="text-[10px] text-slate-500 font-black uppercase">App Versie</span><span className="font-mono">{t('version') || '2.1.34'}</span></div>
          </div>
       </div>
    </div>
  );
};
