
import React, { useState, useEffect, useRef } from 'react';
import { Upload, Save, Image as ImageIcon, CheckCircle2, AlertCircle, MessageSquare, Trash2, Database, Copy, RefreshCw, LayoutGrid, Tag, Layers, Plus, Activity, Users, Clock, Crown, Loader2, X, Disc, AlertTriangle, PieChart as PieChartIcon, ChevronRight, History, Check, Search } from 'lucide-react';
import { PieChart, Pie, Cell, ResponsiveContainer, Tooltip } from 'recharts';
import { supabase } from '../services/supabase';
import { useLogo } from '../contexts/LogoContext';
import { useLanguage } from '../contexts/LanguageContext';

type AdminTab = 'dashboard' | 'users' | 'sql' | 'logo' | 'spools' | 'data' | 'feedback' | 'requests';

const COLORS = ['#3b82f6', '#10b981', '#f59e0b', '#ef4444', '#8b5cf6', '#ec4899', '#06b6d4', '#64748b'];

const MASTER_SQL = `-- 1. PROFIELEN
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  is_pro boolean default false,
  showcase_name text,
  updated_at timestamptz default now()
);
alter table public.profiles enable row level security;
create policy "Users can view own profile" on public.profiles for select using (auth.uid() = id);
create policy "Users can update own profile" on public.profiles for update using (auth.uid() = id);

-- 2. ADMIN VIEW: Gebruikers Statistieken
-- Eerst verwijderen om kolomnaam-fouten te voorkomen
drop view if exists public.admin_user_stats;

create view public.admin_user_stats as
select 
  p.id,
  u.email,
  p.is_pro,
  u.created_at,
  (select count(*) from public.filaments f where f.user_id = p.id) as filament_count,
  (select count(*) from public.print_jobs pj where pj.user_id = p.id) as print_count
from public.profiles p
join auth.users u on u.id = p.id;

-- 3. GLOBAL TABLES
create table if not exists public.spool_weights (
  id uuid default gen_random_uuid() primary key,
  name text unique not null,
  weight numeric not null
);
create table if not exists public.brands (id uuid default gen_random_uuid() primary key, name text unique not null);
create table if not exists public.materials (id uuid default gen_random_uuid() primary key, name text unique not null);
create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  message text not null,
  rating smallint,
  user_id uuid references auth.users(id) on delete cascade,
  is_read boolean default false,
  platform text,
  user_agent text
);
create table if not exists public.deletion_requests (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users(id) on delete cascade,
  email text,
  reason text,
  created_at timestamptz default now()
);
create table if not exists public.global_settings (key text primary key, value text);`;

interface AdminPanelProps {
  onClose?: () => void;
}

export const AdminPanel: React.FC<AdminPanelProps> = ({ onClose }) => {
  const { refreshLogo } = useLogo();
  const { t } = useLanguage();
  const [activeTab, setActiveTab] = useState<AdminTab>('dashboard');
  
  // States
  const [users, setUsers] = useState<any[]>([]);
  const [feedbacks, setFeedbacks] = useState<any[]>([]);
  const [requests, setRequests] = useState<any[]>([]);
  const [spoolWeights, setSpoolWeights] = useState<any[]>([]);
  const [brands, setBrands] = useState<any[]>([]);
  const [materials, setMaterials] = useState<any[]>([]);
  const [tableCounts, setTableCounts] = useState({ logs: 0, filaments: 0, proUsers: 0, totalUsers: 0 });
  const [platformMaterialData, setPlatformMaterialData] = useState<any[]>([]);
  
  // Loading & UI States
  const [isLoading, setIsLoading] = useState(false);
  const [updatingUserId, setUpdatingUserId] = useState<string | null>(null);
  const [latency, setLatency] = useState<number | null>(null);
  const [sqlCopied, setSqlCopied] = useState(false);
  const [previewUrl, setPreviewUrl] = useState<string | null>(null);
  const [isUploading, setIsUploading] = useState(false);

  // Form States
  const [newSpool, setNewSpool] = useState({ name: '', weight: '' });
  const [newBrand, setNewBrand] = useState('');
  const [newMaterial, setNewMaterial] = useState('');

  const fileInputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    loadDashboardStats();
    checkLatency();
    if (activeTab === 'feedback') loadFeedback();
    if (activeTab === 'requests') loadRequests();
    if (activeTab === 'users') loadUsers();
    if (activeTab === 'spools') loadSpoolWeights();
    if (activeTab === 'data') { loadBrands(); loadMaterials(); }
  }, [activeTab]);

  const checkLatency = async () => {
    const start = performance.now();
    try {
      await supabase.from('profiles').select('id').limit(1);
      setLatency(Math.round(performance.now() - start));
    } catch (e) { setLatency(null); }
  };

  const loadDashboardStats = async () => {
    try {
      const { count: lCount } = await supabase.from('print_jobs').select('*', { count: 'exact', head: true });
      const { count: fCount } = await supabase.from('filaments').select('*', { count: 'exact', head: true });
      const { count: uCount } = await supabase.from('profiles').select('*', { count: 'exact', head: true });
      const { count: pCount } = await supabase.from('profiles').select('*', { count: 'exact', head: true }).eq('is_pro', true);
      setTableCounts({ logs: lCount || 0, filaments: fCount || 0, totalUsers: uCount || 0, proUsers: pCount || 0 });
      
      const { data: filamentStats } = await supabase.from('filaments').select('material');
      if (filamentStats) {
        const counts: Record<string, number> = {};
        filamentStats.forEach((f: any) => { 
           const mat = f.material || 'PLA';
           counts[mat] = (counts[mat] || 0) + 1; 
        });
        setPlatformMaterialData(Object.entries(counts).map(([name, value]) => ({ name, value })).slice(0, 5));
      }
    } catch (e) { console.error(e); }
  };

  const loadUsers = async () => {
    setIsLoading(true);
    try {
      const { data } = await supabase.from('admin_user_stats').select('*').order('created_at', { ascending: false });
      setUsers(data || []);
    } catch (e) { console.error(e); }
    setIsLoading(false);
  };

  const toggleProStatus = async (userId: string, currentStatus: boolean) => {
    setUpdatingUserId(userId);
    try {
      await supabase.from('profiles').update({ is_pro: !currentStatus }).eq('id', userId);
      setUsers(prev => prev.map(u => u.id === userId ? { ...u, is_pro: !currentStatus } : u));
      loadDashboardStats();
    } catch (e) { alert("Bijwerken mislukt"); }
    setUpdatingUserId(null);
  };

  const handleCopySql = () => {
    navigator.clipboard.writeText(MASTER_SQL);
    setSqlCopied(true);
    setTimeout(() => setSqlCopied(false), 2000);
  };

  const loadSpoolWeights = async () => {
    const { data } = await supabase.from('spool_weights').select('*').order('name');
    if (data) setSpoolWeights(data);
  };
  const addSpoolWeight = async () => {
    if (!newSpool.name || !newSpool.weight) return;
    const { error } = await supabase.from('spool_weights').insert({ name: newSpool.name, weight: parseFloat(newSpool.weight) });
    if (error) alert(error.message); else { setNewSpool({ name: '', weight: '' }); loadSpoolWeights(); }
  };
  const deleteSpoolWeight = async (id: string) => {
    await supabase.from('spool_weights').delete().eq('id', id);
    loadSpoolWeights();
  };

  const loadRequests = async () => {
    const { data } = await supabase.from('deletion_requests').select('*').order('created_at', { ascending: false });
    if (data) setRequests(data);
  };
  const deleteRequest = async (id: string) => {
    await supabase.from('deletion_requests').delete().eq('id', id);
    loadRequests();
  };

  const loadBrands = async () => { 
     try {
        const { data } = await supabase.from('brands').select('*').order('name'); 
        if (data) setBrands(data); 
     } catch (e) { console.warn("Brands table might not exist"); }
  };
  const addBrand = async () => { 
     const { error } = await supabase.from('brands').insert({ name: newBrand }); 
     if (error) alert(error.message);
     setNewBrand(''); 
     loadBrands(); 
  };
  const deleteBrand = async (id: string) => { await supabase.from('brands').delete().eq('id', id); loadBrands(); };
  
  const loadMaterials = async () => { 
     try {
        const { data } = await supabase.from('materials').select('*').order('name'); 
        if (data) setMaterials(data); 
     } catch (e) { console.warn("Materials table might not exist"); }
  };
  const addMaterial = async () => { 
     const { error } = await supabase.from('materials').insert({ name: newMaterial }); 
     if (error) alert(error.message);
     setNewMaterial(''); 
     loadMaterials(); 
  };
  const deleteMaterial = async (id: string) => { await supabase.from('materials').delete().eq('id', id); loadMaterials(); };

  const loadFeedback = async () => {
    const { data } = await supabase.from('feedback').select('*').order('created_at', { ascending: false });
    if (data) setFeedbacks(data);
  };
  const toggleFeedbackRead = async (id: number, isRead: boolean) => {
    await supabase.from('feedback').update({ is_read: !isRead }).eq('id', id);
    loadFeedback();
  };

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => setPreviewUrl(reader.result as string);
      reader.readAsDataURL(file);
    }
  };
  const handleLogoUpload = async () => {
    if (!previewUrl) return;
    setIsUploading(true);
    await supabase.from('global_settings').upsert({ key: 'app_logo', value: previewUrl });
    await refreshLogo();
    setIsUploading(false);
    alert("Logo bijgewerkt!");
  };

  return (
    <div className="max-w-7xl mx-auto pb-20 animate-fade-in flex flex-col gap-6">
      {/* Navigation */}
      <div className="bg-white dark:bg-slate-800 rounded-2xl shadow-sm border border-slate-200 dark:border-slate-700 p-2 flex items-center overflow-x-auto gap-2 scrollbar-hide">
        {[
          { id: 'dashboard', icon: LayoutGrid, label: 'Dashboard' },
          { id: 'users', icon: Users, label: 'Gebruikers' },
          { id: 'sql', icon: Database, label: 'SQL Tool' },
          { id: 'spools', icon: Disc, label: 'Spoelen' },
          { id: 'requests', icon: AlertTriangle, label: 'Verzoeken' },
          { id: 'data', icon: Tag, label: 'Merken/Mats' },
          { id: 'logo', icon: ImageIcon, label: 'Logo' },
          { id: 'feedback', icon: MessageSquare, label: 'Feedback' },
        ].map(tab => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id as AdminTab)}
            className={`flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-black uppercase tracking-widest transition-all whitespace-nowrap ${activeTab === tab.id ? 'bg-blue-600 text-white shadow-lg' : 'text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-700'}`}
          >
            <tab.icon size={16} /> {tab.label}
          </button>
        ))}
      </div>

      <div className="min-h-[500px]">
        {activeTab === 'dashboard' && (
          <div className="space-y-6">
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              <div className="bg-white dark:bg-slate-800 p-6 rounded-2xl border border-slate-200 shadow-sm">
                <p className="text-slate-500 text-[10px] font-black uppercase mb-1">Gebruikers</p>
                <p className="text-3xl font-black dark:text-white">{tableCounts.totalUsers}</p>
              </div>
              <div className="bg-white dark:bg-slate-800 p-6 rounded-2xl border border-slate-200 shadow-sm">
                <p className="text-amber-500 text-[10px] font-black uppercase mb-1">PRO Leden</p>
                <p className="text-3xl font-black text-amber-500">{tableCounts.proUsers}</p>
              </div>
              <div className="bg-white dark:bg-slate-800 p-6 rounded-2xl border border-slate-200 shadow-sm">
                <p className="text-blue-500 text-[10px] font-black uppercase mb-1">Totaal Spoelen</p>
                <p className="text-3xl font-black dark:text-white">{tableCounts.filaments}</p>
              </div>
              <div className="bg-white dark:bg-slate-800 p-6 rounded-2xl border border-slate-200 shadow-sm">
                <p className="text-emerald-500 text-[10px] font-black uppercase mb-1">Database Latency</p>
                <p className="text-3xl font-black text-emerald-500">{latency ? `${latency}ms` : '---'}</p>
              </div>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              <div className="bg-white dark:bg-slate-800 p-8 rounded-[32px] border border-slate-200 shadow-sm h-80">
                <h3 className="font-bold mb-6 flex items-center gap-2 dark:text-white"><PieChartIcon size={20} className="text-blue-500" /> Top Materialen</h3>
                <ResponsiveContainer width="100%" height="100%">
                  <PieChart>
                    <Pie data={platformMaterialData} cx="50%" cy="50%" innerRadius={60} outerRadius={80} paddingAngle={5} dataKey="value">
                      {platformMaterialData.map((_, i) => <Cell key={i} fill={COLORS[i % COLORS.length]} />)}
                    </Pie>
                    <Tooltip />
                  </PieChart>
                </ResponsiveContainer>
              </div>
              <div className="bg-white dark:bg-slate-800 p-8 rounded-[32px] border border-slate-200 shadow-sm">
                <h3 className="font-bold mb-4 flex items-center gap-2 dark:text-white"><Activity size={20} className="text-orange-500" /> Systeem</h3>
                <div className="space-y-3">
                   <div className="p-4 bg-slate-50 dark:bg-slate-900 rounded-xl flex justify-between items-center text-sm font-bold">
                      <span className="text-slate-500">Supabase Status</span>
                      <span className="text-emerald-500">ONLINE</span>
                   </div>
                   <div className="p-4 bg-slate-50 dark:bg-slate-900 rounded-xl flex justify-between items-center text-sm font-bold">
                      <span className="text-slate-500">AI Engine</span>
                      <span className="text-blue-500">ACTIVE</span>
                   </div>
                </div>
              </div>
            </div>
          </div>
        )}

        {activeTab === 'users' && (
          <div className="bg-white dark:bg-slate-800 rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
            <div className="p-6 border-b flex justify-between items-center bg-slate-50 dark:bg-slate-900/50">
              <h3 className="font-bold dark:text-white">Gebruikers ({users.length})</h3>
              <button onClick={loadUsers} className="p-2 text-blue-500 hover:bg-blue-50 rounded-lg"><RefreshCw size={18}/></button>
            </div>
            <div className="overflow-x-auto">
               <table className="w-full text-left">
               <thead>
                  <tr className="bg-slate-50 dark:bg-slate-900 text-[10px] font-black uppercase text-slate-500 border-b">
                     <th className="p-4">Email</th>
                     <th className="p-4 text-center">Status</th>
                     <th className="p-4 text-center">Data</th>
                  </tr>
               </thead>
               <tbody className="divide-y">
                  {users.map(u => (
                     <tr key={u.id} className="text-sm dark:text-white hover:bg-slate-50 dark:hover:bg-slate-700/30">
                     <td className="p-4">
                        <div className="font-bold">{u.email}</div>
                        <div className="text-[10px] text-slate-400 font-mono">Sinds: {new Date(u.created_at).toLocaleDateString()}</div>
                     </td>
                     <td className="p-4 text-center">
                        <button 
                           onClick={() => toggleProStatus(u.id, u.is_pro)}
                           disabled={updatingUserId === u.id}
                           className={`px-3 py-1.5 rounded-full text-[10px] font-black uppercase tracking-tighter transition-all ${u.is_pro ? 'bg-amber-100 text-amber-600 border border-amber-200' : 'bg-slate-100 text-slate-500 border border-slate-200'}`}
                        >
                           {updatingUserId === u.id ? <Loader2 size={12} className="animate-spin"/> : (u.is_pro ? 'PRO MEMBER' : 'MAKE PRO')}
                        </button>
                     </td>
                     <td className="p-4 text-center">
                        <div className="flex justify-center gap-2">
                           <span className="text-[10px] font-bold px-2 py-1 bg-blue-50 dark:bg-blue-900/30 text-blue-600 rounded-md border border-blue-100">{u.filament_count || 0} spools</span>
                           <span className="text-[10px] font-bold px-2 py-1 bg-emerald-50 dark:bg-emerald-900/30 text-emerald-600 rounded-md border border-emerald-100">{u.print_count || 0} logs</span>
                        </div>
                     </td>
                     </tr>
                  ))}
               </tbody>
               </table>
            </div>
          </div>
        )}

        {activeTab === 'sql' && (
          <div className="space-y-6">
            <div className="bg-amber-50 dark:bg-amber-900/20 p-6 rounded-2xl border border-amber-200 flex gap-4 items-start">
               <AlertCircle className="text-amber-600 shrink-0" size={24}/>
               <div>
                  <h4 className="font-bold text-amber-800 dark:text-amber-400">Database Setup</h4>
                  <p className="text-sm text-amber-700 dark:text-amber-500/80">Kopieer de onderstaande SQL en voer deze uit in de Supabase SQL Editor om alle benodigde tabellen, views en triggers in één keer aan te maken.</p>
               </div>
            </div>
            <div className="bg-slate-900 rounded-2xl overflow-hidden relative border border-slate-700 shadow-2xl">
               <div className="flex justify-between items-center p-4 border-b border-slate-800 bg-slate-800/50">
                  <span className="text-slate-400 font-mono text-xs">master_setup.sql</span>
                  <button 
                    onClick={handleCopySql}
                    className={`flex items-center gap-2 px-4 py-2 rounded-lg text-xs font-bold transition-all ${sqlCopied ? 'bg-emerald-500 text-white' : 'bg-blue-600 text-white hover:bg-blue-500'}`}
                  >
                     {sqlCopied ? <Check size={14}/> : <Copy size={14}/>}
                     {sqlCopied ? 'Gekopieerd!' : 'SQL Kopiëren'}
                  </button>
               </div>
               <pre className="p-6 text-emerald-400 font-mono text-xs overflow-x-auto max-h-[400px] leading-relaxed">
                  {MASTER_SQL}
               </pre>
            </div>
          </div>
        )}

        {activeTab === 'spools' && (
          <div className="space-y-6">
            <div className="bg-white dark:bg-slate-800 p-6 rounded-2xl border border-slate-200 shadow-sm">
               <h3 className="font-bold mb-4 dark:text-white">Nieuw Spoelgewicht</h3>
               <div className="grid grid-cols-2 md:grid-cols-3 gap-4 items-end">
                  <input type="text" placeholder="Naam (bijv. Bambu Lab Karton)" value={newSpool.name} onChange={e => setNewSpool({...newSpool, name: e.target.value})} className="bg-slate-50 dark:bg-slate-900 border border-slate-200 rounded-xl p-3 text-sm dark:text-white" />
                  <input type="number" placeholder="Gewicht (gram)" value={newSpool.weight} onChange={e => setNewSpool({...newSpool, weight: e.target.value})} className="bg-slate-50 dark:bg-slate-900 border border-slate-200 rounded-xl p-3 text-sm dark:text-white" />
                  <button onClick={addSpoolWeight} className="bg-blue-600 text-white font-bold py-3 rounded-xl hover:bg-blue-500 transition-all flex items-center justify-center gap-2"><Plus size={18}/> Toevoegen</button>
               </div>
            </div>
            <div className="bg-white dark:bg-slate-800 rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
               <table className="w-full text-left">
                  <thead className="bg-slate-50 dark:bg-slate-900 text-[10px] font-black text-slate-500 uppercase border-b">
                    <tr><th className="p-4">Spoel Type</th><th className="p-4">Gewicht</th><th className="p-4 text-right">Actie</th></tr>
                  </thead>
                  <tbody>
                    {spoolWeights.map(sw => (
                       <tr key={sw.id} className="text-sm dark:text-white border-b last:border-0 hover:bg-slate-50 dark:hover:bg-slate-700/30">
                          <td className="p-4 font-bold">{sw.name}</td>
                          <td className="p-4">{sw.weight}g</td>
                          <td className="p-4 text-right"><button onClick={() => deleteSpoolWeight(sw.id)} className="text-red-400 hover:text-red-600"><Trash2 size={16}/></button></td>
                       </tr>
                    ))}
                  </tbody>
               </table>
            </div>
          </div>
        )}

        {activeTab === 'requests' && (
          <div className="bg-white dark:bg-slate-800 rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
             <div className="p-6 border-b flex justify-between items-center bg-red-50/30 dark:bg-red-900/10">
                <h3 className="font-bold text-red-600">Verwijderverzoeken ({requests.length})</h3>
                <button onClick={loadRequests} className="p-2 text-red-500 hover:bg-red-50 rounded-lg"><RefreshCw size={18}/></button>
             </div>
             <table className="w-full text-left">
                <thead className="bg-slate-50 dark:bg-slate-900 text-[10px] font-black text-slate-500 uppercase border-b">
                   <tr><th className="p-4">Account</th><th className="p-4">Reden</th><th className="p-4">Datum</th><th className="p-4 text-right">Actie</th></tr>
                </thead>
                <tbody>
                   {requests.map(r => (
                      <tr key={r.id} className="text-xs dark:text-white border-b hover:bg-slate-50">
                         <td className="p-4 font-bold">{r.email}</td>
                         <td className="p-4 italic text-slate-500">{r.reason}</td>
                         <td className="p-4">{new Date(r.created_at).toLocaleDateString()}</td>
                         <td className="p-4 text-right">
                            <button onClick={() => deleteRequest(r.id)} className="text-slate-400 hover:text-blue-500 mr-2"><Check size={16}/></button>
                            <button className="text-red-400 hover:text-red-600"><Trash2 size={16}/></button>
                         </td>
                      </tr>
                   ))}
                   {requests.length === 0 && <tr><td colSpan={4} className="p-10 text-center text-slate-400 italic">Geen verzoeken gevonden</td></tr>}
                </tbody>
             </table>
          </div>
        )}

        {activeTab === 'data' && (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="bg-white dark:bg-slate-800 p-6 rounded-2xl border shadow-sm flex flex-col">
               <h3 className="font-bold mb-4 dark:text-white">Presets: Merken</h3>
               <div className="flex gap-2 mb-4">
                  <input type="text" placeholder="Merk naam" value={newBrand} onChange={e => setNewBrand(e.target.value)} className="flex-1 bg-slate-50 dark:bg-slate-900 border rounded-xl p-2 text-sm dark:text-white" />
                  <button onClick={addBrand} className="bg-blue-600 text-white p-2 rounded-xl"><Plus size={20}/></button>
               </div>
               <div className="max-h-64 overflow-y-auto divide-y dark:divide-slate-700">
                  {brands.map(b => (
                     <div key={b.id} className="flex justify-between items-center py-2">
                        <span className="text-sm dark:text-slate-300">{b.name}</span>
                        <button onClick={() => deleteBrand(b.id)} className="text-slate-300 hover:text-red-500"><Trash2 size={14}/></button>
                     </div>
                  ))}
               </div>
            </div>
            <div className="bg-white dark:bg-slate-800 p-6 rounded-2xl border shadow-sm flex flex-col">
               <h3 className="font-bold mb-4 dark:text-white">Presets: Materialen</h3>
               <div className="flex gap-2 mb-4">
                  <input type="text" placeholder="Materiaal" value={newMaterial} onChange={e => setNewMaterial(e.target.value)} className="flex-1 bg-slate-50 dark:bg-slate-900 border rounded-xl p-2 text-sm dark:text-white" />
                  <button onClick={addMaterial} className="bg-blue-600 text-white p-2 rounded-xl"><Plus size={20}/></button>
               </div>
               <div className="max-h-64 overflow-y-auto divide-y dark:divide-slate-700">
                  {materials.map(m => (
                     <div key={m.id} className="flex justify-between items-center py-2">
                        <span className="text-sm dark:text-slate-300">{m.name}</span>
                        <button onClick={() => deleteMaterial(m.id)} className="text-slate-300 hover:text-red-500"><Trash2 size={14}/></button>
                     </div>
                  ))}
               </div>
            </div>
          </div>
        )}

        {activeTab === 'logo' && (
          <div className="bg-white dark:bg-slate-800 p-8 rounded-[32px] border border-slate-200 shadow-sm max-w-xl mx-auto text-center">
             <h3 className="font-bold text-xl mb-6 dark:text-white">App Logo Aanpassen</h3>
             <div onClick={() => fileInputRef.current?.click()} className="group aspect-square max-w-[200px] mx-auto rounded-[40px] border-4 border-dashed border-slate-200 flex flex-col items-center justify-center cursor-pointer hover:border-blue-500 transition-all overflow-hidden bg-slate-50 dark:bg-slate-900">
                {previewUrl ? <img src={previewUrl} className="w-full h-full object-contain p-4" /> : <ImageIcon size={48} className="text-slate-300" />}
                <input type="file" ref={fileInputRef} onChange={handleFileSelect} accept="image/*" className="hidden" />
             </div>
             <p className="mt-4 text-xs text-slate-400">Klik hierboven om een afbeelding te kiezen. <br/>Aanbevolen: PNG of SVG (vierkant).</p>
             <button onClick={handleLogoUpload} disabled={!previewUrl || isUploading} className="w-full mt-8 bg-blue-600 text-white font-bold py-4 rounded-2xl disabled:opacity-50 flex items-center justify-center gap-2">
                {isUploading ? <Loader2 className="animate-spin" size={20}/> : <Save size={20}/>}
                Opslaan & Bijwerken
             </button>
          </div>
        )}

        {activeTab === 'feedback' && (
           <div className="bg-white dark:bg-slate-800 rounded-2xl border shadow-sm overflow-hidden">
              <div className="p-6 border-b flex justify-between bg-purple-50/30 dark:bg-purple-900/10"><h3 className="font-bold dark:text-white">Feedback ({feedbacks.length})</h3></div>
              <div className="overflow-x-auto">
                 <table className="w-full text-left">
                    <thead>
                       <tr className="bg-slate-50 dark:bg-slate-900 text-[10px] font-black uppercase text-slate-500 border-b">
                          <th className="p-4">Bericht</th>
                          <th className="p-4 text-center">Rating</th>
                          <th className="p-4 text-right">Actie</th>
                       </tr>
                    </thead>
                    <tbody>
                       {feedbacks.map(f => (
                          <tr key={f.id} className={`text-sm border-b last:border-0 dark:text-white hover:bg-slate-50 ${!f.is_read ? 'bg-purple-50/20' : ''}`}>
                             <td className="p-4"><p className="max-w-md line-clamp-2">{f.message}</p></td>
                             <td className="p-4 text-center font-bold text-amber-500">{f.rating}/5</td>
                             <td className="p-4 text-right">
                                <button onClick={() => toggleFeedbackRead(f.id, f.is_read)} className={`p-2 rounded-lg ${f.is_read ? 'text-slate-400' : 'text-blue-500'}`}><CheckCircle2 size={18}/></button>
                                <button className="p-2 text-red-400"><Trash2 size={18}/></button>
                             </td>
                          </tr>
                       ))}
                    </tbody>
                 </table>
              </div>
           </div>
        )}
      </div>
    </div>
  );
};
